// Canonical country list with ISO-2 codes for flag emojis and dial codes.
// Use across all phone/nationality dropdowns site-wide.

export interface Country {
  name: string;
  iso: string; // ISO 3166-1 alpha-2
  code: string; // dial code, e.g. "+971"
}

export const COUNTRIES: Country[] = [
  { name: "United Arab Emirates", iso: "AE", code: "+971" },
  { name: "Saudi Arabia", iso: "SA", code: "+966" },
  { name: "Qatar", iso: "QA", code: "+974" },
  { name: "Kuwait", iso: "KW", code: "+965" },
  { name: "Oman", iso: "OM", code: "+968" },
  { name: "Bahrain", iso: "BH", code: "+973" },
  { name: "Yemen", iso: "YE", code: "+967" },
  { name: "Iraq", iso: "IQ", code: "+964" },
  { name: "Iran", iso: "IR", code: "+98" },
  { name: "Syria", iso: "SY", code: "+963" },
  { name: "Lebanon", iso: "LB", code: "+961" },
  { name: "Jordan", iso: "JO", code: "+962" },
  { name: "Palestine", iso: "PS", code: "+970" },
  { name: "Israel", iso: "IL", code: "+972" },
  { name: "Türkiye", iso: "TR", code: "+90" },
  { name: "Cyprus", iso: "CY", code: "+357" },
  { name: "Egypt", iso: "EG", code: "+20" },
  { name: "Libya", iso: "LY", code: "+218" },
  { name: "Tunisia", iso: "TN", code: "+216" },
  { name: "Algeria", iso: "DZ", code: "+213" },
  { name: "Morocco", iso: "MA", code: "+212" },
  { name: "Sudan", iso: "SD", code: "+249" },
  { name: "South Sudan", iso: "SS", code: "+211" },
  { name: "Ethiopia", iso: "ET", code: "+251" },
  { name: "Kenya", iso: "KE", code: "+254" },
  { name: "Uganda", iso: "UG", code: "+256" },
  { name: "Tanzania", iso: "TZ", code: "+255" },
  { name: "Rwanda", iso: "RW", code: "+250" },
  { name: "Nigeria", iso: "NG", code: "+234" },
  { name: "Ghana", iso: "GH", code: "+233" },
  { name: "Senegal", iso: "SN", code: "+221" },
  { name: "Ivory Coast", iso: "CI", code: "+225" },
  { name: "Cameroon", iso: "CM", code: "+237" },
  { name: "Angola", iso: "AO", code: "+244" },
  { name: "South Africa", iso: "ZA", code: "+27" },
  { name: "Zimbabwe", iso: "ZW", code: "+263" },
  { name: "Mozambique", iso: "MZ", code: "+258" },
  { name: "Mauritius", iso: "MU", code: "+230" },
  { name: "Seychelles", iso: "SC", code: "+248" },
  { name: "United Kingdom", iso: "GB", code: "+44" },
  { name: "Ireland", iso: "IE", code: "+353" },
  { name: "France", iso: "FR", code: "+33" },
  { name: "Monaco", iso: "MC", code: "+377" },
  { name: "Germany", iso: "DE", code: "+49" },
  { name: "Austria", iso: "AT", code: "+43" },
  { name: "Switzerland", iso: "CH", code: "+41" },
  { name: "Liechtenstein", iso: "LI", code: "+423" },
  { name: "Luxembourg", iso: "LU", code: "+352" },
  { name: "Belgium", iso: "BE", code: "+32" },
  { name: "Netherlands", iso: "NL", code: "+31" },
  { name: "Denmark", iso: "DK", code: "+45" },
  { name: "Norway", iso: "NO", code: "+47" },
  { name: "Sweden", iso: "SE", code: "+46" },
  { name: "Finland", iso: "FI", code: "+358" },
  { name: "Iceland", iso: "IS", code: "+354" },
  { name: "Estonia", iso: "EE", code: "+372" },
  { name: "Latvia", iso: "LV", code: "+371" },
  { name: "Lithuania", iso: "LT", code: "+370" },
  { name: "Poland", iso: "PL", code: "+48" },
  { name: "Czechia", iso: "CZ", code: "+420" },
  { name: "Slovakia", iso: "SK", code: "+421" },
  { name: "Hungary", iso: "HU", code: "+36" },
  { name: "Romania", iso: "RO", code: "+40" },
  { name: "Bulgaria", iso: "BG", code: "+359" },
  { name: "Greece", iso: "GR", code: "+30" },
  { name: "Italy", iso: "IT", code: "+39" },
  { name: "Vatican City", iso: "VA", code: "+39" },
  { name: "San Marino", iso: "SM", code: "+378" },
  { name: "Malta", iso: "MT", code: "+356" },
  { name: "Spain", iso: "ES", code: "+34" },
  { name: "Portugal", iso: "PT", code: "+351" },
  { name: "Andorra", iso: "AD", code: "+376" },
  { name: "Slovenia", iso: "SI", code: "+386" },
  { name: "Croatia", iso: "HR", code: "+385" },
  { name: "Bosnia and Herzegovina", iso: "BA", code: "+387" },
  { name: "Serbia", iso: "RS", code: "+381" },
  { name: "Montenegro", iso: "ME", code: "+382" },
  { name: "North Macedonia", iso: "MK", code: "+389" },
  { name: "Albania", iso: "AL", code: "+355" },
  { name: "Kosovo", iso: "XK", code: "+383" },
  { name: "Moldova", iso: "MD", code: "+373" },
  { name: "Ukraine", iso: "UA", code: "+380" },
  { name: "Belarus", iso: "BY", code: "+375" },
  { name: "Russia", iso: "RU", code: "+7" },
  { name: "Kazakhstan", iso: "KZ", code: "+7" },
  { name: "Uzbekistan", iso: "UZ", code: "+998" },
  { name: "Turkmenistan", iso: "TM", code: "+993" },
  { name: "Tajikistan", iso: "TJ", code: "+992" },
  { name: "Kyrgyzstan", iso: "KG", code: "+996" },
  { name: "Azerbaijan", iso: "AZ", code: "+994" },
  { name: "Armenia", iso: "AM", code: "+374" },
  { name: "Georgia", iso: "GE", code: "+995" },
  { name: "Afghanistan", iso: "AF", code: "+93" },
  { name: "Pakistan", iso: "PK", code: "+92" },
  { name: "India", iso: "IN", code: "+91" },
  { name: "Nepal", iso: "NP", code: "+977" },
  { name: "Bhutan", iso: "BT", code: "+975" },
  { name: "Bangladesh", iso: "BD", code: "+880" },
  { name: "Sri Lanka", iso: "LK", code: "+94" },
  { name: "Maldives", iso: "MV", code: "+960" },
  { name: "Myanmar", iso: "MM", code: "+95" },
  { name: "Thailand", iso: "TH", code: "+66" },
  { name: "Laos", iso: "LA", code: "+856" },
  { name: "Cambodia", iso: "KH", code: "+855" },
  { name: "Vietnam", iso: "VN", code: "+84" },
  { name: "Malaysia", iso: "MY", code: "+60" },
  { name: "Singapore", iso: "SG", code: "+65" },
  { name: "Indonesia", iso: "ID", code: "+62" },
  { name: "Philippines", iso: "PH", code: "+63" },
  { name: "Brunei", iso: "BN", code: "+673" },
  { name: "China", iso: "CN", code: "+86" },
  { name: "Hong Kong", iso: "HK", code: "+852" },
  { name: "Macau", iso: "MO", code: "+853" },
  { name: "Taiwan", iso: "TW", code: "+886" },
  { name: "Mongolia", iso: "MN", code: "+976" },
  { name: "Japan", iso: "JP", code: "+81" },
  { name: "South Korea", iso: "KR", code: "+82" },
  { name: "North Korea", iso: "KP", code: "+850" },
  { name: "Australia", iso: "AU", code: "+61" },
  { name: "New Zealand", iso: "NZ", code: "+64" },
  { name: "Fiji", iso: "FJ", code: "+679" },
  { name: "Papua New Guinea", iso: "PG", code: "+675" },
  { name: "United States", iso: "US", code: "+1" },
  { name: "Canada", iso: "CA", code: "+1" },
  { name: "Mexico", iso: "MX", code: "+52" },
  { name: "Guatemala", iso: "GT", code: "+502" },
  { name: "Belize", iso: "BZ", code: "+501" },
  { name: "Honduras", iso: "HN", code: "+504" },
  { name: "El Salvador", iso: "SV", code: "+503" },
  { name: "Nicaragua", iso: "NI", code: "+505" },
  { name: "Costa Rica", iso: "CR", code: "+506" },
  { name: "Panama", iso: "PA", code: "+507" },
  { name: "Cuba", iso: "CU", code: "+53" },
  { name: "Jamaica", iso: "JM", code: "+1876" },
  { name: "Dominican Republic", iso: "DO", code: "+1809" },
  { name: "Haiti", iso: "HT", code: "+509" },
  { name: "Puerto Rico", iso: "PR", code: "+1787" },
  { name: "Trinidad and Tobago", iso: "TT", code: "+1868" },
  { name: "Barbados", iso: "BB", code: "+1246" },
  { name: "Bahamas", iso: "BS", code: "+1242" },
  { name: "Colombia", iso: "CO", code: "+57" },
  { name: "Venezuela", iso: "VE", code: "+58" },
  { name: "Guyana", iso: "GY", code: "+592" },
  { name: "Suriname", iso: "SR", code: "+597" },
  { name: "Ecuador", iso: "EC", code: "+593" },
  { name: "Peru", iso: "PE", code: "+51" },
  { name: "Bolivia", iso: "BO", code: "+591" },
  { name: "Brazil", iso: "BR", code: "+55" },
  { name: "Paraguay", iso: "PY", code: "+595" },
  { name: "Uruguay", iso: "UY", code: "+598" },
  { name: "Argentina", iso: "AR", code: "+54" },
  { name: "Chile", iso: "CL", code: "+56" },
];

// Convert ISO-2 country code (e.g. "AE") to the corresponding regional-indicator flag emoji.
export function flagEmoji(iso: string): string {
  if (!iso || iso.length !== 2) return "";
  const base = 0x1f1e6;
  const A = "A".charCodeAt(0);
  const up = iso.toUpperCase();
  return String.fromCodePoint(base + (up.charCodeAt(0) - A)) +
    String.fromCodePoint(base + (up.charCodeAt(1) - A));
}
