/**
 * REVENUE ATTRIBUTION TYPES
 * JBJ GLOBAL REAL ESTATE | BUY · SELL · RENT
 * 
 * Type definitions for deal conversion attribution and revenue tracking.
 * ALL revenue is generated by JBJ GLOBAL REAL ESTATE.
 */

import type { PartnerType } from '@/config/partner-types';

// ============================================================
// ORIGINATING CHANNELS
// ============================================================

export type OriginatingChannel = 'website' | 'data_partner' | 'referral' | 'internal';

export const ORIGINATING_CHANNELS: OriginatingChannel[] = [
  'website',
  'data_partner',
  'referral',
  'internal',
];

// ============================================================
// EXECUTION MODELS
// ============================================================

export type ExecutionModel = 'A' | 'B' | 'C';

export const EXECUTION_MODELS: ExecutionModel[] = ['A', 'B', 'C'];

export const EXECUTION_MODEL_DESCRIPTIONS: Record<ExecutionModel, {
  name: string;
  description: string;
  partner_execution: boolean;
  commission_applicable: boolean;
  notes: string;
}> = {
  A: {
    name: 'Full Ownership',
    description: 'JBJ GLOBAL REAL ESTATE executes directly with full control',
    partner_execution: false,
    commission_applicable: true,
    notes: 'Origin commission only - JBJ GLOBAL REAL ESTATE executes directly',
  },
  B: {
    name: 'Partner Execution',
    description: 'Licensed partner executes on behalf of JBJ GLOBAL REAL ESTATE',
    partner_execution: true,
    commission_applicable: true,
    notes: 'Both origin and execution commission possible',
  },
  C: {
    name: 'Intelligence Only',
    description: 'Data/market intelligence provision only - NO transaction execution',
    partner_execution: false,
    commission_applicable: false,
    notes: 'NO COMMISSION - Intelligence only model',
  },
};

// ============================================================
// DEAL STATUS
// ============================================================

export type DealStatus = 'pending' | 'in_progress' | 'closed' | 'cancelled' | 'expired';

export const DEAL_STATUSES: DealStatus[] = ['pending', 'in_progress', 'closed', 'cancelled', 'expired'];

// ============================================================
// DEAL CONVERSION RECORD (MANDATORY STRUCTURE)
// ============================================================

export interface DealConversionRecord {
  /** Unique deal identifier */
  deal_id: string;
  /** Channel that originated this deal */
  originating_channel: OriginatingChannel;
  /** Partner that originated the deal (nullable) */
  originating_partner_id: string | null;
  /** Jurisdiction where deal occurred */
  jurisdiction_id: string;
  /** Execution model used */
  execution_model: ExecutionModel;
  /** Partner executing the deal (nullable - only for Model B) */
  executing_partner_id: string | null;
  /** Assigned broker ID */
  assigned_broker_id: string;
  /** Client ID (owned by JBJ GLOBAL REAL ESTATE) */
  client_id: string;
  /** When the conversion occurred */
  conversion_timestamp: string;
  /** Deal status */
  status: DealStatus;
  /** Deal value */
  deal_value: number;
  /** Currency */
  currency: string;
  /** Is attribution locked (immutable once closed) */
  attribution_locked: boolean;
  /** When attribution was locked */
  attribution_locked_at: string | null;
  /** Created timestamp */
  created_at: string;
  /** Updated timestamp */
  updated_at: string;
}

// ============================================================
// COMMISSION BASIS
// ============================================================

export type CommissionBasis = 'percentage' | 'fixed_fee';

// ============================================================
// COMMISSION APPLIES TO
// ============================================================

export type CommissionAppliesTo = 'origin' | 'execution' | 'both';

// ============================================================
// COMMISSION STATUS
// ============================================================

export type CommissionConfigStatus = 'active' | 'expired' | 'suspended';

// ============================================================
// COMMISSION CONFIGURATION (PER PARTNER)
// ============================================================

export interface PartnerCommissionConfig {
  /** Unique config ID */
  config_id: string;
  /** Partner ID */
  partner_id: string;
  /** Partner type */
  partner_type: PartnerType;
  /** Jurisdiction this config applies to */
  jurisdiction_id: string;
  /** Basis for commission calculation */
  commission_basis: CommissionBasis;
  /** Commission rate (percentage as decimal or fixed amount) */
  commission_rate: number;
  /** Currency for fixed fee */
  currency?: string;
  /** What this commission applies to */
  applies_to: CommissionAppliesTo;
  /** Config start date */
  start_date: string;
  /** Config end date (nullable for indefinite) */
  end_date: string | null;
  /** Config status */
  status: CommissionConfigStatus;
  /** Created timestamp */
  created_at: string;
  /** Created by */
  created_by: string;
  /** Updated timestamp */
  updated_at: string;
  /** Updated by */
  updated_by: string;
}

// ============================================================
// COMMISSION RECORD (GENERATED - READ ONLY)
// ============================================================

export interface CommissionRecord {
  /** Unique commission ID */
  commission_id: string;
  /** Associated deal ID */
  deal_id: string;
  /** Partner receiving commission */
  partner_id: string;
  /** Partner type */
  partner_type: PartnerType;
  /** Commission config used */
  config_id: string;
  /** Commission type (origin / execution) */
  commission_type: 'origin' | 'execution';
  /** Deal value used for calculation */
  deal_value: number;
  /** Calculated commission amount */
  commission_amount: number;
  /** Currency */
  currency: string;
  /** Commission basis used */
  commission_basis: CommissionBasis;
  /** Rate applied */
  rate_applied: number;
  /** Jurisdiction */
  jurisdiction_id: string;
  /** Execution model */
  execution_model: ExecutionModel;
  /** Generated timestamp */
  generated_at: string;
  /** Is record locked (always true after generation) */
  is_locked: true;
  /** Audit reference */
  audit_id: string;
}

// ============================================================
// COMMISSION AUDIT LOG
// ============================================================

export interface CommissionAuditLog {
  /** Audit ID */
  audit_id: string;
  /** Commission ID */
  commission_id: string;
  /** Deal ID */
  deal_id: string;
  /** Action */
  action: 'generated' | 'viewed' | 'exported';
  /** Actor user ID */
  actor_user_id: string;
  /** Actor role */
  actor_role: string;
  /** Timestamp */
  timestamp: string;
  /** IP address */
  ip_address?: string;
}
