// JBJ Global Real Estate - Broker Directory
// 128 Professional Real Estate Brokers

export interface Broker {
  id: string;
  name: string;
  nationality: string;
  gender: 'male' | 'female';
  languages: string[];
  specializations: string[];
  yearsExperience: number;
  email: string;
  phone: string;
  bio: string;
}

// Helper to generate email from name
const generateEmail = (name: string): string => {
  const nameParts = name.toLowerCase().split(' ');
  return `${nameParts[0]}.${nameParts[nameParts.length - 1]}@jbj.ae`;
};

// Helper to generate phone
const generatePhone = (index: number): string => {
  const base = 500000000 + index * 1111;
  return `+971 5${Math.floor(base / 10000000) % 10} ${Math.floor(base / 10000) % 1000} ${base % 10000}`;
};

export const allBrokers: Broker[] = [
  // British Brokers (25)
  {
    id: 'broker-001',
    name: 'James Crawford',
    nationality: 'British',
    gender: 'male',
    languages: ['English', 'Arabic'],
    specializations: ['Luxury Villas', 'Palm Jumeirah'],
    yearsExperience: 12,
    email: generateEmail('James Crawford'),
    phone: generatePhone(1),
    bio: 'Expert in ultra-luxury waterfront properties with a keen eye for architectural excellence.',
  },
  {
    id: 'broker-002',
    name: 'Charlotte Webb',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'French'],
    specializations: ['Downtown Dubai', 'High-Rise Apartments'],
    yearsExperience: 8,
    email: generateEmail('Charlotte Webb'),
    phone: generatePhone(2),
    bio: 'Passionate about modern urban living and connecting clients with their dream homes.',
  },
  {
    id: 'broker-003',
    name: 'William Foster',
    nationality: 'British',
    gender: 'male',
    languages: ['English'],
    specializations: ['Commercial Properties', 'Investment'],
    yearsExperience: 15,
    email: generateEmail('William Foster'),
    phone: generatePhone(3),
    bio: 'Seasoned commercial real estate advisor with strong investor relationships.',
  },
  {
    id: 'broker-004',
    name: 'Sophie Reynolds',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'Spanish'],
    specializations: ['Off-Plan Properties', 'First-Time Buyers'],
    yearsExperience: 6,
    email: generateEmail('Sophie Reynolds'),
    phone: generatePhone(4),
    bio: 'Dedicated to helping clients navigate the exciting world of off-plan investments.',
  },
  {
    id: 'broker-005',
    name: 'Edward Hartley',
    nationality: 'British',
    gender: 'male',
    languages: ['English', 'Arabic'],
    specializations: ['Dubai Hills', 'Family Homes'],
    yearsExperience: 10,
    email: generateEmail('Edward Hartley'),
    phone: generatePhone(5),
    bio: 'Family-focused broker specializing in community living and lifestyle properties.',
  },
  {
    id: 'broker-006',
    name: 'Eleanor Marshall',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'Italian'],
    specializations: ['Penthouses', 'Exclusive Listings'],
    yearsExperience: 11,
    email: generateEmail('Eleanor Marshall'),
    phone: generatePhone(6),
    bio: 'Curates exclusive penthouse properties for discerning high-net-worth clients.',
  },
  {
    id: 'broker-007',
    name: 'Henry Collins',
    nationality: 'British',
    gender: 'male',
    languages: ['English'],
    specializations: ['Marina', 'JBR'],
    yearsExperience: 9,
    email: generateEmail('Henry Collins'),
    phone: generatePhone(7),
    bio: 'Marina lifestyle expert with comprehensive knowledge of waterfront communities.',
  },
  {
    id: 'broker-008',
    name: 'Victoria Shaw',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'French'],
    specializations: ['Luxury Rentals', 'Corporate Relocations'],
    yearsExperience: 7,
    email: generateEmail('Victoria Shaw'),
    phone: generatePhone(8),
    bio: 'Specializes in seamless corporate relocations and premium rental solutions.',
  },
  {
    id: 'broker-009',
    name: 'George Whitfield',
    nationality: 'British',
    gender: 'male',
    languages: ['English', 'Arabic'],
    specializations: ['Emirates Hills', 'Golf Communities'],
    yearsExperience: 14,
    email: generateEmail('George Whitfield'),
    phone: generatePhone(9),
    bio: 'Premier golf community specialist with access to the most exclusive addresses.',
  },
  {
    id: 'broker-010',
    name: 'Amelia Norton',
    nationality: 'British',
    gender: 'female',
    languages: ['English'],
    specializations: ['New Developments', 'Investment Analysis'],
    yearsExperience: 5,
    email: generateEmail('Amelia Norton'),
    phone: generatePhone(10),
    bio: 'Data-driven approach to identifying the best investment opportunities.',
  },
  {
    id: 'broker-011',
    name: 'Thomas Burke',
    nationality: 'British',
    gender: 'male',
    languages: ['English', 'German'],
    specializations: ['Business Bay', 'Commercial Rentals'],
    yearsExperience: 13,
    email: generateEmail('Thomas Burke'),
    phone: generatePhone(11),
    bio: 'Business Bay authority with extensive commercial and residential portfolio.',
  },
  {
    id: 'broker-012',
    name: 'Isabelle Clarke',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'Arabic'],
    specializations: ['Jumeirah', 'Beachfront Properties'],
    yearsExperience: 8,
    email: generateEmail('Isabelle Clarke'),
    phone: generatePhone(12),
    bio: 'Beachfront property specialist with deep Jumeirah market knowledge.',
  },
  {
    id: 'broker-013',
    name: 'Frederick Hayes',
    nationality: 'British',
    gender: 'male',
    languages: ['English'],
    specializations: ['DIFC', 'Premium Offices'],
    yearsExperience: 16,
    email: generateEmail('Frederick Hayes'),
    phone: generatePhone(13),
    bio: 'DIFC and financial district expert for corporate headquarters.',
  },
  {
    id: 'broker-014',
    name: 'Harriet Palmer',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'Spanish'],
    specializations: ['Townhouses', 'Community Living'],
    yearsExperience: 7,
    email: generateEmail('Harriet Palmer'),
    phone: generatePhone(14),
    bio: 'Community-focused broker helping families find their perfect neighborhood.',
  },
  {
    id: 'broker-015',
    name: 'Sebastian Moore',
    nationality: 'British',
    gender: 'male',
    languages: ['English', 'French'],
    specializations: ['Bluewaters Island', 'Premium Developments'],
    yearsExperience: 6,
    email: generateEmail('Sebastian Moore'),
    phone: generatePhone(15),
    bio: 'Premium island living specialist with exclusive Bluewaters access.',
  },
  {
    id: 'broker-016',
    name: 'Olivia Bennett',
    nationality: 'British',
    gender: 'female',
    languages: ['English'],
    specializations: ['Creek Harbour', 'Waterfront'],
    yearsExperience: 4,
    email: generateEmail('Olivia Bennett'),
    phone: generatePhone(16),
    bio: 'Creek Harbour enthusiast passionate about emerging waterfront communities.',
  },
  {
    id: 'broker-017',
    name: 'Alexander Price',
    nationality: 'British',
    gender: 'male',
    languages: ['English', 'Arabic'],
    specializations: ['Arabian Ranches', 'Villas'],
    yearsExperience: 11,
    email: generateEmail('Alexander Price'),
    phone: generatePhone(17),
    bio: 'Arabian Ranches expert with comprehensive villa portfolio.',
  },
  {
    id: 'broker-018',
    name: 'Grace Henderson',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'Russian'],
    specializations: ['Luxury Apartments', 'City Views'],
    yearsExperience: 9,
    email: generateEmail('Grace Henderson'),
    phone: generatePhone(18),
    bio: 'High-rise luxury apartment specialist with panoramic view properties.',
  },
  {
    id: 'broker-019',
    name: 'Nathaniel Wright',
    nationality: 'British',
    gender: 'male',
    languages: ['English'],
    specializations: ['MBR City', 'New Projects'],
    yearsExperience: 5,
    email: generateEmail('Nathaniel Wright'),
    phone: generatePhone(19),
    bio: 'Future-focused broker tracking MBR City development opportunities.',
  },
  {
    id: 'broker-020',
    name: 'Beatrice Cooper',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'French'],
    specializations: ['City Walk', 'Urban Living'],
    yearsExperience: 6,
    email: generateEmail('Beatrice Cooper'),
    phone: generatePhone(20),
    bio: 'Urban lifestyle expert specializing in walkable city neighborhoods.',
  },
  {
    id: 'broker-021',
    name: 'Jonathan Ellis',
    nationality: 'British',
    gender: 'male',
    languages: ['English', 'Arabic'],
    specializations: ['Meydan', 'Equestrian'],
    yearsExperience: 12,
    email: generateEmail('Jonathan Ellis'),
    phone: generatePhone(21),
    bio: 'Meydan and equestrian community specialist for lifestyle buyers.',
  },
  {
    id: 'broker-022',
    name: 'Catherine Ross',
    nationality: 'British',
    gender: 'female',
    languages: ['English'],
    specializations: ['Studio Apartments', 'Young Professionals'],
    yearsExperience: 4,
    email: generateEmail('Catherine Ross'),
    phone: generatePhone(22),
    bio: 'Helping young professionals find their first Dubai property.',
  },
  {
    id: 'broker-023',
    name: 'Arthur Stevens',
    nationality: 'British',
    gender: 'male',
    languages: ['English', 'Spanish'],
    specializations: ['Sports City', 'Affordable Luxury'],
    yearsExperience: 8,
    email: generateEmail('Arthur Stevens'),
    phone: generatePhone(23),
    bio: 'Value-focused broker finding affordable luxury options.',
  },
  {
    id: 'broker-024',
    name: 'Emma Richardson',
    nationality: 'British',
    gender: 'female',
    languages: ['English', 'Italian'],
    specializations: ['La Mer', 'Beach Living'],
    yearsExperience: 7,
    email: generateEmail('Emma Richardson'),
    phone: generatePhone(24),
    bio: 'Beach lifestyle specialist with La Mer expertise.',
  },
  {
    id: 'broker-025',
    name: 'Daniel Hughes',
    nationality: 'British',
    gender: 'male',
    languages: ['English'],
    specializations: ['JVC', 'Emerging Areas'],
    yearsExperience: 6,
    email: generateEmail('Daniel Hughes'),
    phone: generatePhone(25),
    bio: 'Emerging neighborhoods expert identifying growth areas.',
  },

  // French Brokers (20)
  {
    id: 'broker-026',
    name: 'Antoine Dubois',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English', 'Arabic'],
    specializations: ['Luxury Villas', 'French Clientele'],
    yearsExperience: 14,
    email: generateEmail('Antoine Dubois'),
    phone: generatePhone(26),
    bio: 'Premier French-speaking broker serving European investors.',
  },
  {
    id: 'broker-027',
    name: 'Camille Laurent',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English'],
    specializations: ['Downtown Dubai', 'Investment Properties'],
    yearsExperience: 10,
    email: generateEmail('Camille Laurent'),
    phone: generatePhone(27),
    bio: 'Investment specialist connecting French investors with Dubai opportunities.',
  },
  {
    id: 'broker-028',
    name: 'Pierre Moreau',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English', 'Spanish'],
    specializations: ['Palm Jumeirah', 'Waterfront'],
    yearsExperience: 12,
    email: generateEmail('Pierre Moreau'),
    phone: generatePhone(28),
    bio: 'Waterfront property expert with European design sensibility.',
  },
  {
    id: 'broker-029',
    name: 'Sophie Martin',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English', 'Italian'],
    specializations: ['Penthouses', 'Designer Homes'],
    yearsExperience: 8,
    email: generateEmail('Sophie Martin'),
    phone: generatePhone(29),
    bio: 'Curates designer properties for clients with refined taste.',
  },
  {
    id: 'broker-030',
    name: 'Julien Bernard',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English'],
    specializations: ['Commercial', 'Retail Spaces'],
    yearsExperience: 15,
    email: generateEmail('Julien Bernard'),
    phone: generatePhone(30),
    bio: 'Commercial real estate advisor for retail and F&B brands.',
  },
  {
    id: 'broker-031',
    name: 'Margot Petit',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English', 'Arabic'],
    specializations: ['Off-Plan', 'New Developments'],
    yearsExperience: 6,
    email: generateEmail('Margot Petit'),
    phone: generatePhone(31),
    bio: 'Off-plan specialist helping clients secure best launch prices.',
  },
  {
    id: 'broker-032',
    name: 'Nicolas Girard',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English'],
    specializations: ['Emirates Hills', 'Luxury Estates'],
    yearsExperience: 11,
    email: generateEmail('Nicolas Girard'),
    phone: generatePhone(32),
    bio: 'Ultra-luxury estate specialist for discerning European buyers.',
  },
  {
    id: 'broker-033',
    name: 'Amélie Rousseau',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English', 'German'],
    specializations: ['Marina', 'Yacht Owners'],
    yearsExperience: 9,
    email: generateEmail('Amélie Rousseau'),
    phone: generatePhone(33),
    bio: 'Marina lifestyle expert catering to yacht owners and maritime enthusiasts.',
  },
  {
    id: 'broker-034',
    name: 'Étienne Lefevre',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English'],
    specializations: ['Bluewaters', 'Island Living'],
    yearsExperience: 7,
    email: generateEmail('Étienne Lefevre'),
    phone: generatePhone(34),
    bio: 'Island living specialist with exclusive Bluewaters portfolio.',
  },
  {
    id: 'broker-035',
    name: 'Chloé Dupont',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English', 'Spanish'],
    specializations: ['City Walk', 'Boutique Living'],
    yearsExperience: 5,
    email: generateEmail('Chloé Dupont'),
    phone: generatePhone(35),
    bio: 'Boutique property expert for urban sophisticates.',
  },
  {
    id: 'broker-036',
    name: 'Vincent Mercier',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English', 'Arabic'],
    specializations: ['DIFC', 'Corporate'],
    yearsExperience: 13,
    email: generateEmail('Vincent Mercier'),
    phone: generatePhone(36),
    bio: 'DIFC specialist serving corporate executives and financiers.',
  },
  {
    id: 'broker-037',
    name: 'Léa Bonnet',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English'],
    specializations: ['Jumeirah', 'Beachfront'],
    yearsExperience: 8,
    email: generateEmail('Léa Bonnet'),
    phone: generatePhone(37),
    bio: 'Beachfront living specialist with Jumeirah expertise.',
  },
  {
    id: 'broker-038',
    name: 'Maxime Fournier',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English'],
    specializations: ['Business Bay', 'Modern Living'],
    yearsExperience: 6,
    email: generateEmail('Maxime Fournier'),
    phone: generatePhone(38),
    bio: 'Modern living advocate in Dubai business districts.',
  },
  {
    id: 'broker-039',
    name: 'Inès Blanc',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English', 'Italian'],
    specializations: ['Townhouses', 'Family Homes'],
    yearsExperience: 7,
    email: generateEmail('Inès Blanc'),
    phone: generatePhone(39),
    bio: 'Family-focused broker for European families relocating to Dubai.',
  },
  {
    id: 'broker-040',
    name: 'Alexandre Chevalier',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English'],
    specializations: ['Dubai Hills', 'Golf Views'],
    yearsExperience: 10,
    email: generateEmail('Alexandre Chevalier'),
    phone: generatePhone(40),
    bio: 'Golf community expert for sports enthusiasts.',
  },
  {
    id: 'broker-041',
    name: 'Clara Renard',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English', 'Arabic'],
    specializations: ['Luxury Rentals', 'Short-Term'],
    yearsExperience: 5,
    email: generateEmail('Clara Renard'),
    phone: generatePhone(41),
    bio: 'Premium rental specialist for luxury short-term stays.',
  },
  {
    id: 'broker-042',
    name: 'Théo Lambert',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English'],
    specializations: ['Creek Harbour', 'Waterfront'],
    yearsExperience: 4,
    email: generateEmail('Théo Lambert'),
    phone: generatePhone(42),
    bio: 'Creek Harbour enthusiast for waterfront living.',
  },
  {
    id: 'broker-043',
    name: 'Manon Gauthier',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English'],
    specializations: ['Arabian Ranches', 'Villas'],
    yearsExperience: 8,
    email: generateEmail('Manon Gauthier'),
    phone: generatePhone(43),
    bio: 'Villa specialist in premier community developments.',
  },
  {
    id: 'broker-044',
    name: 'Hugo Perrin',
    nationality: 'French',
    gender: 'male',
    languages: ['French', 'English', 'Spanish'],
    specializations: ['Investment', 'Portfolio'],
    yearsExperience: 12,
    email: generateEmail('Hugo Perrin'),
    phone: generatePhone(44),
    bio: 'Investment portfolio advisor for European investors.',
  },
  {
    id: 'broker-045',
    name: 'Juliette Simon',
    nationality: 'French',
    gender: 'female',
    languages: ['French', 'English'],
    specializations: ['MBR City', 'Lagoon Living'],
    yearsExperience: 6,
    email: generateEmail('Juliette Simon'),
    phone: generatePhone(45),
    bio: 'MBR City specialist focusing on lagoon communities.',
  },

  // Brazilian Brokers (20)
  {
    id: 'broker-046',
    name: 'Lucas Silva',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Luxury Villas', 'Latin American Clients'],
    yearsExperience: 10,
    email: generateEmail('Lucas Silva'),
    phone: generatePhone(46),
    bio: 'Premier Portuguese-speaking broker for Latin American investors.',
  },
  {
    id: 'broker-047',
    name: 'Gabriela Santos',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Downtown Dubai', 'High-Rise'],
    yearsExperience: 8,
    email: generateEmail('Gabriela Santos'),
    phone: generatePhone(47),
    bio: 'Downtown specialist connecting Brazilian buyers with prime properties.',
  },
  {
    id: 'broker-048',
    name: 'Rafael Oliveira',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Palm Jumeirah', 'Beachfront'],
    yearsExperience: 12,
    email: generateEmail('Rafael Oliveira'),
    phone: generatePhone(48),
    bio: 'Beachfront lifestyle expert for South American clients.',
  },
  {
    id: 'broker-049',
    name: 'Isabela Costa',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Marina', 'Waterfront Living'],
    yearsExperience: 7,
    email: generateEmail('Isabela Costa'),
    phone: generatePhone(49),
    bio: 'Marina living specialist with Brazilian flair.',
  },
  {
    id: 'broker-050',
    name: 'Thiago Pereira',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Investment', 'Off-Plan'],
    yearsExperience: 9,
    email: generateEmail('Thiago Pereira'),
    phone: generatePhone(50),
    bio: 'Investment advisor specializing in off-plan opportunities.',
  },
  {
    id: 'broker-051',
    name: 'Mariana Rodrigues',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Penthouses', 'Luxury Apartments'],
    yearsExperience: 6,
    email: generateEmail('Mariana Rodrigues'),
    phone: generatePhone(51),
    bio: 'Luxury apartment curator for discerning clients.',
  },
  {
    id: 'broker-052',
    name: 'Fernando Almeida',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Commercial', 'Business Properties'],
    yearsExperience: 14,
    email: generateEmail('Fernando Almeida'),
    phone: generatePhone(52),
    bio: 'Commercial real estate expert for Brazilian businesses.',
  },
  {
    id: 'broker-053',
    name: 'Larissa Ferreira',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Dubai Hills', 'Family Homes'],
    yearsExperience: 5,
    email: generateEmail('Larissa Ferreira'),
    phone: generatePhone(53),
    bio: 'Family-focused broker for Brazilian families in Dubai.',
  },
  {
    id: 'broker-054',
    name: 'Bruno Souza',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['JBR', 'Beach Living'],
    yearsExperience: 8,
    email: generateEmail('Bruno Souza'),
    phone: generatePhone(54),
    bio: 'JBR lifestyle expert for beach lovers.',
  },
  {
    id: 'broker-055',
    name: 'Carolina Lima',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['City Walk', 'Urban Living'],
    yearsExperience: 6,
    email: generateEmail('Carolina Lima'),
    phone: generatePhone(55),
    bio: 'Urban lifestyle specialist for modern living.',
  },
  {
    id: 'broker-056',
    name: 'Marcos Cardoso',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Emirates Hills', 'Luxury Estates'],
    yearsExperience: 11,
    email: generateEmail('Marcos Cardoso'),
    phone: generatePhone(56),
    bio: 'Ultra-luxury specialist for high-net-worth clients.',
  },
  {
    id: 'broker-057',
    name: 'Amanda Martins',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Bluewaters', 'Island Properties'],
    yearsExperience: 4,
    email: generateEmail('Amanda Martins'),
    phone: generatePhone(57),
    bio: 'Island living enthusiast for exclusive addresses.',
  },
  {
    id: 'broker-058',
    name: 'Ricardo Barbosa',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Business Bay', 'Modern Apartments'],
    yearsExperience: 7,
    email: generateEmail('Ricardo Barbosa'),
    phone: generatePhone(58),
    bio: 'Business Bay specialist for young professionals.',
  },
  {
    id: 'broker-059',
    name: 'Juliana Ribeiro',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Arabian Ranches', 'Villas'],
    yearsExperience: 9,
    email: generateEmail('Juliana Ribeiro'),
    phone: generatePhone(59),
    bio: 'Villa community expert for families.',
  },
  {
    id: 'broker-060',
    name: 'Paulo Mendes',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['DIFC', 'Premium Offices'],
    yearsExperience: 13,
    email: generateEmail('Paulo Mendes'),
    phone: generatePhone(60),
    bio: 'DIFC expert for Brazilian businesses.',
  },
  {
    id: 'broker-061',
    name: 'Camila Araújo',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Jumeirah', 'Beachfront Villas'],
    yearsExperience: 8,
    email: generateEmail('Camila Araújo'),
    phone: generatePhone(61),
    bio: 'Jumeirah villa specialist for beachfront living.',
  },
  {
    id: 'broker-062',
    name: 'Eduardo Gomes',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Creek Harbour', 'Waterfront'],
    yearsExperience: 5,
    email: generateEmail('Eduardo Gomes'),
    phone: generatePhone(62),
    bio: 'Creek Harbour advocate for waterfront communities.',
  },
  {
    id: 'broker-063',
    name: 'Fernanda Carvalho',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Luxury Rentals', 'Corporate'],
    yearsExperience: 6,
    email: generateEmail('Fernanda Carvalho'),
    phone: generatePhone(63),
    bio: 'Premium rental solutions for corporate clients.',
  },
  {
    id: 'broker-064',
    name: 'Guilherme Nascimento',
    nationality: 'Brazilian',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Sports City', 'Active Living'],
    yearsExperience: 7,
    email: generateEmail('Guilherme Nascimento'),
    phone: generatePhone(64),
    bio: 'Active lifestyle communities for sports enthusiasts.',
  },
  {
    id: 'broker-065',
    name: 'Beatriz Castro',
    nationality: 'Brazilian',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['La Mer', 'Beach Communities'],
    yearsExperience: 4,
    email: generateEmail('Beatriz Castro'),
    phone: generatePhone(65),
    bio: 'La Mer specialist for beach community living.',
  },

  // Portuguese Brokers (15)
  {
    id: 'broker-066',
    name: 'João Fernandes',
    nationality: 'Portuguese',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Luxury Properties', 'European Clients'],
    yearsExperience: 11,
    email: generateEmail('João Fernandes'),
    phone: generatePhone(66),
    bio: 'Premier broker for Portuguese-speaking European investors.',
  },
  {
    id: 'broker-067',
    name: 'Ana Sousa',
    nationality: 'Portuguese',
    gender: 'female',
    languages: ['Portuguese', 'English', 'French'],
    specializations: ['Downtown Dubai', 'Investment'],
    yearsExperience: 9,
    email: generateEmail('Ana Sousa'),
    phone: generatePhone(67),
    bio: 'Investment specialist for European capital.',
  },
  {
    id: 'broker-068',
    name: 'Miguel Teixeira',
    nationality: 'Portuguese',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Palm Jumeirah', 'Waterfront'],
    yearsExperience: 10,
    email: generateEmail('Miguel Teixeira'),
    phone: generatePhone(68),
    bio: 'Waterfront property expert with Mediterranean sensibility.',
  },
  {
    id: 'broker-069',
    name: 'Inês Marques',
    nationality: 'Portuguese',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Marina', 'Yacht Lifestyle'],
    yearsExperience: 7,
    email: generateEmail('Inês Marques'),
    phone: generatePhone(69),
    bio: 'Marina lifestyle specialist for yachting community.',
  },
  {
    id: 'broker-070',
    name: 'Tiago Pinto',
    nationality: 'Portuguese',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Commercial', 'Retail'],
    yearsExperience: 13,
    email: generateEmail('Tiago Pinto'),
    phone: generatePhone(70),
    bio: 'Commercial real estate advisor for Portuguese businesses.',
  },
  {
    id: 'broker-071',
    name: 'Sofia Correia',
    nationality: 'Portuguese',
    gender: 'female',
    languages: ['Portuguese', 'English', 'French'],
    specializations: ['Penthouses', 'Luxury Living'],
    yearsExperience: 8,
    email: generateEmail('Sofia Correia'),
    phone: generatePhone(71),
    bio: 'Penthouse curator for discerning European buyers.',
  },
  {
    id: 'broker-072',
    name: 'André Lopes',
    nationality: 'Portuguese',
    gender: 'male',
    languages: ['Portuguese', 'English'],
    specializations: ['Dubai Hills', 'Golf Communities'],
    yearsExperience: 6,
    email: generateEmail('André Lopes'),
    phone: generatePhone(72),
    bio: 'Golf community specialist for active lifestyles.',
  },
  {
    id: 'broker-073',
    name: 'Maria Alves',
    nationality: 'Portuguese',
    gender: 'female',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Family Homes', 'Community Living'],
    yearsExperience: 5,
    email: generateEmail('Maria Alves'),
    phone: generatePhone(73),
    bio: 'Family-focused broker for European families.',
  },
  {
    id: 'broker-074',
    name: 'Diogo Santos',
    nationality: 'Portuguese',
    gender: 'male',
    languages: ['Portuguese', 'English'],
    specializations: ['Business Bay', 'Urban Living'],
    yearsExperience: 7,
    email: generateEmail('Diogo Santos'),
    phone: generatePhone(74),
    bio: 'Urban living specialist in business districts.',
  },
  {
    id: 'broker-075',
    name: 'Beatriz Oliveira',
    nationality: 'Portuguese',
    gender: 'female',
    languages: ['Portuguese', 'English', 'French'],
    specializations: ['Jumeirah', 'Beach Properties'],
    yearsExperience: 6,
    email: generateEmail('Beatriz Oliveira'),
    phone: generatePhone(75),
    bio: 'Beachfront specialist for coastal living.',
  },
  {
    id: 'broker-076',
    name: 'Pedro Machado',
    nationality: 'Portuguese',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Off-Plan', 'New Projects'],
    yearsExperience: 8,
    email: generateEmail('Pedro Machado'),
    phone: generatePhone(76),
    bio: 'Off-plan investment specialist.',
  },
  {
    id: 'broker-077',
    name: 'Catarina Rocha',
    nationality: 'Portuguese',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['City Walk', 'Boutique Living'],
    yearsExperience: 4,
    email: generateEmail('Catarina Rocha'),
    phone: generatePhone(77),
    bio: 'Boutique property expert for urban sophisticates.',
  },
  {
    id: 'broker-078',
    name: 'Rui Ferreira',
    nationality: 'Portuguese',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Emirates Hills', 'Luxury Estates'],
    yearsExperience: 12,
    email: generateEmail('Rui Ferreira'),
    phone: generatePhone(78),
    bio: 'Ultra-luxury estate specialist.',
  },
  {
    id: 'broker-079',
    name: 'Marta Costa',
    nationality: 'Portuguese',
    gender: 'female',
    languages: ['Portuguese', 'English'],
    specializations: ['Creek Harbour', 'Waterfront'],
    yearsExperience: 5,
    email: generateEmail('Marta Costa'),
    phone: generatePhone(79),
    bio: 'Creek Harbour waterfront specialist.',
  },
  {
    id: 'broker-080',
    name: 'Nuno Gonçalves',
    nationality: 'Portuguese',
    gender: 'male',
    languages: ['Portuguese', 'English', 'Spanish'],
    specializations: ['Arabian Ranches', 'Villas'],
    yearsExperience: 9,
    email: generateEmail('Nuno Gonçalves'),
    phone: generatePhone(80),
    bio: 'Villa community expert for family living.',
  },

  // American Brokers (20)
  {
    id: 'broker-081',
    name: 'Michael Thompson',
    nationality: 'American',
    gender: 'male',
    languages: ['English', 'Spanish'],
    specializations: ['Luxury Villas', 'US Clients'],
    yearsExperience: 15,
    email: generateEmail('Michael Thompson'),
    phone: generatePhone(81),
    bio: 'Premier broker serving American investors in Dubai.',
  },
  {
    id: 'broker-082',
    name: 'Jennifer Williams',
    nationality: 'American',
    gender: 'female',
    languages: ['English'],
    specializations: ['Downtown Dubai', 'High-Rise'],
    yearsExperience: 10,
    email: generateEmail('Jennifer Williams'),
    phone: generatePhone(82),
    bio: 'Downtown specialist for American relocations.',
  },
  {
    id: 'broker-083',
    name: 'Christopher Davis',
    nationality: 'American',
    gender: 'male',
    languages: ['English', 'Arabic'],
    specializations: ['Palm Jumeirah', 'Beachfront'],
    yearsExperience: 12,
    email: generateEmail('Christopher Davis'),
    phone: generatePhone(83),
    bio: 'Beachfront expert for American families.',
  },
  {
    id: 'broker-084',
    name: 'Ashley Johnson',
    nationality: 'American',
    gender: 'female',
    languages: ['English', 'French'],
    specializations: ['Marina', 'Waterfront Living'],
    yearsExperience: 8,
    email: generateEmail('Ashley Johnson'),
    phone: generatePhone(84),
    bio: 'Marina lifestyle specialist.',
  },
  {
    id: 'broker-085',
    name: 'Brandon Miller',
    nationality: 'American',
    gender: 'male',
    languages: ['English'],
    specializations: ['Investment', 'Commercial'],
    yearsExperience: 14,
    email: generateEmail('Brandon Miller'),
    phone: generatePhone(85),
    bio: 'Commercial investment advisor for US investors.',
  },
  {
    id: 'broker-086',
    name: 'Lauren Anderson',
    nationality: 'American',
    gender: 'female',
    languages: ['English', 'Spanish'],
    specializations: ['Penthouses', 'Luxury Apartments'],
    yearsExperience: 7,
    email: generateEmail('Lauren Anderson'),
    phone: generatePhone(86),
    bio: 'Luxury apartment curator for American clients.',
  },
  {
    id: 'broker-087',
    name: 'Ryan Taylor',
    nationality: 'American',
    gender: 'male',
    languages: ['English'],
    specializations: ['Emirates Hills', 'Golf Estates'],
    yearsExperience: 11,
    email: generateEmail('Ryan Taylor'),
    phone: generatePhone(87),
    bio: 'Golf estate specialist for American buyers.',
  },
  {
    id: 'broker-088',
    name: 'Megan Wilson',
    nationality: 'American',
    gender: 'female',
    languages: ['English', 'Arabic'],
    specializations: ['Dubai Hills', 'Family Homes'],
    yearsExperience: 6,
    email: generateEmail('Megan Wilson'),
    phone: generatePhone(88),
    bio: 'Family home specialist for American relocations.',
  },
  {
    id: 'broker-089',
    name: 'Kyle Martinez',
    nationality: 'American',
    gender: 'male',
    languages: ['English', 'Spanish'],
    specializations: ['JBR', 'Beach Living'],
    yearsExperience: 9,
    email: generateEmail('Kyle Martinez'),
    phone: generatePhone(89),
    bio: 'Beach lifestyle expert for active clients.',
  },
  {
    id: 'broker-090',
    name: 'Nicole Garcia',
    nationality: 'American',
    gender: 'female',
    languages: ['English', 'Spanish'],
    specializations: ['City Walk', 'Urban Living'],
    yearsExperience: 5,
    email: generateEmail('Nicole Garcia'),
    phone: generatePhone(90),
    bio: 'Urban lifestyle specialist for young professionals.',
  },
  {
    id: 'broker-091',
    name: 'Tyler Robinson',
    nationality: 'American',
    gender: 'male',
    languages: ['English'],
    specializations: ['Business Bay', 'Modern Apartments'],
    yearsExperience: 7,
    email: generateEmail('Tyler Robinson'),
    phone: generatePhone(91),
    bio: 'Business Bay specialist for American executives.',
  },
  {
    id: 'broker-092',
    name: 'Stephanie Lee',
    nationality: 'American',
    gender: 'female',
    languages: ['English', 'Chinese'],
    specializations: ['Bluewaters', 'Island Living'],
    yearsExperience: 4,
    email: generateEmail('Stephanie Lee'),
    phone: generatePhone(92),
    bio: 'Island living specialist for unique addresses.',
  },
  {
    id: 'broker-093',
    name: 'Jason White',
    nationality: 'American',
    gender: 'male',
    languages: ['English', 'Arabic'],
    specializations: ['Arabian Ranches', 'Villas'],
    yearsExperience: 10,
    email: generateEmail('Jason White'),
    phone: generatePhone(93),
    bio: 'Villa community expert for family living.',
  },
  {
    id: 'broker-094',
    name: 'Samantha Brown',
    nationality: 'American',
    gender: 'female',
    languages: ['English'],
    specializations: ['DIFC', 'Corporate'],
    yearsExperience: 8,
    email: generateEmail('Samantha Brown'),
    phone: generatePhone(94),
    bio: 'DIFC specialist for corporate clients.',
  },
  {
    id: 'broker-095',
    name: 'Andrew Harris',
    nationality: 'American',
    gender: 'male',
    languages: ['English', 'Spanish'],
    specializations: ['Jumeirah', 'Beachfront Villas'],
    yearsExperience: 12,
    email: generateEmail('Andrew Harris'),
    phone: generatePhone(95),
    bio: 'Jumeirah villa specialist.',
  },
  {
    id: 'broker-096',
    name: 'Amanda King',
    nationality: 'American',
    gender: 'female',
    languages: ['English', 'French'],
    specializations: ['Off-Plan', 'New Developments'],
    yearsExperience: 6,
    email: generateEmail('Amanda King'),
    phone: generatePhone(96),
    bio: 'Off-plan specialist for investment opportunities.',
  },
  {
    id: 'broker-097',
    name: 'David Scott',
    nationality: 'American',
    gender: 'male',
    languages: ['English'],
    specializations: ['Creek Harbour', 'Waterfront'],
    yearsExperience: 5,
    email: generateEmail('David Scott'),
    phone: generatePhone(97),
    bio: 'Creek Harbour waterfront specialist.',
  },
  {
    id: 'broker-098',
    name: 'Rachel Green',
    nationality: 'American',
    gender: 'female',
    languages: ['English', 'Spanish'],
    specializations: ['Luxury Rentals', 'Corporate'],
    yearsExperience: 7,
    email: generateEmail('Rachel Green'),
    phone: generatePhone(98),
    bio: 'Premium rental solutions for executives.',
  },
  {
    id: 'broker-099',
    name: 'Matthew Adams',
    nationality: 'American',
    gender: 'male',
    languages: ['English'],
    specializations: ['MBR City', 'Lagoon Living'],
    yearsExperience: 4,
    email: generateEmail('Matthew Adams'),
    phone: generatePhone(99),
    bio: 'MBR City specialist for lagoon communities.',
  },
  {
    id: 'broker-100',
    name: 'Brittany Nelson',
    nationality: 'American',
    gender: 'female',
    languages: ['English', 'Arabic'],
    specializations: ['Townhouses', 'Community Living'],
    yearsExperience: 6,
    email: generateEmail('Brittany Nelson'),
    phone: generatePhone(100),
    bio: 'Townhouse specialist for family communities.',
  },

  // Italian Brokers (10)
  {
    id: 'broker-101',
    name: 'Marco Rossi',
    nationality: 'Italian',
    gender: 'male',
    languages: ['Italian', 'English', 'French'],
    specializations: ['Luxury Villas', 'Design Properties'],
    yearsExperience: 13,
    email: generateEmail('Marco Rossi'),
    phone: generatePhone(101),
    bio: 'Premier Italian broker with design expertise.',
  },
  {
    id: 'broker-102',
    name: 'Giulia Bianchi',
    nationality: 'Italian',
    gender: 'female',
    languages: ['Italian', 'English'],
    specializations: ['Downtown Dubai', 'Luxury Apartments'],
    yearsExperience: 9,
    email: generateEmail('Giulia Bianchi'),
    phone: generatePhone(102),
    bio: 'Downtown luxury specialist for Italian clients.',
  },
  {
    id: 'broker-103',
    name: 'Alessandro Ferrari',
    nationality: 'Italian',
    gender: 'male',
    languages: ['Italian', 'English', 'Spanish'],
    specializations: ['Palm Jumeirah', 'Waterfront'],
    yearsExperience: 11,
    email: generateEmail('Alessandro Ferrari'),
    phone: generatePhone(103),
    bio: 'Waterfront specialist with Mediterranean sensibility.',
  },
  {
    id: 'broker-104',
    name: 'Francesca Conti',
    nationality: 'Italian',
    gender: 'female',
    languages: ['Italian', 'English', 'French'],
    specializations: ['Penthouses', 'Designer Homes'],
    yearsExperience: 8,
    email: generateEmail('Francesca Conti'),
    phone: generatePhone(104),
    bio: 'Designer property curator for refined taste.',
  },
  {
    id: 'broker-105',
    name: 'Luca Romano',
    nationality: 'Italian',
    gender: 'male',
    languages: ['Italian', 'English'],
    specializations: ['Marina', 'Yacht Owners'],
    yearsExperience: 10,
    email: generateEmail('Luca Romano'),
    phone: generatePhone(105),
    bio: 'Marina specialist for yachting community.',
  },
  {
    id: 'broker-106',
    name: 'Valentina Marino',
    nationality: 'Italian',
    gender: 'female',
    languages: ['Italian', 'English', 'French'],
    specializations: ['City Walk', 'Boutique Living'],
    yearsExperience: 6,
    email: generateEmail('Valentina Marino'),
    phone: generatePhone(106),
    bio: 'Boutique living specialist with Italian style.',
  },
  {
    id: 'broker-107',
    name: 'Matteo Colombo',
    nationality: 'Italian',
    gender: 'male',
    languages: ['Italian', 'English', 'Arabic'],
    specializations: ['Emirates Hills', 'Luxury Estates'],
    yearsExperience: 14,
    email: generateEmail('Matteo Colombo'),
    phone: generatePhone(107),
    bio: 'Ultra-luxury estate specialist.',
  },
  {
    id: 'broker-108',
    name: 'Chiara Ricci',
    nationality: 'Italian',
    gender: 'female',
    languages: ['Italian', 'English'],
    specializations: ['Dubai Hills', 'Family Homes'],
    yearsExperience: 5,
    email: generateEmail('Chiara Ricci'),
    phone: generatePhone(108),
    bio: 'Family home specialist for Italian families.',
  },
  {
    id: 'broker-109',
    name: 'Andrea Greco',
    nationality: 'Italian',
    gender: 'male',
    languages: ['Italian', 'English', 'Spanish'],
    specializations: ['Business Bay', 'Investment'],
    yearsExperience: 9,
    email: generateEmail('Andrea Greco'),
    phone: generatePhone(109),
    bio: 'Investment advisor for Italian investors.',
  },
  {
    id: 'broker-110',
    name: 'Elena Bruno',
    nationality: 'Italian',
    gender: 'female',
    languages: ['Italian', 'English', 'French'],
    specializations: ['Jumeirah', 'Beach Properties'],
    yearsExperience: 7,
    email: generateEmail('Elena Bruno'),
    phone: generatePhone(110),
    bio: 'Beach property specialist with Italian flair.',
  },

  // German Brokers (8)
  {
    id: 'broker-111',
    name: 'Hans Müller',
    nationality: 'German',
    gender: 'male',
    languages: ['German', 'English', 'French'],
    specializations: ['Luxury Properties', 'Investment'],
    yearsExperience: 14,
    email: generateEmail('Hans Müller'),
    phone: generatePhone(111),
    bio: 'Premier German-speaking broker for European investors.',
  },
  {
    id: 'broker-112',
    name: 'Anna Schmidt',
    nationality: 'German',
    gender: 'female',
    languages: ['German', 'English'],
    specializations: ['Downtown Dubai', 'High-Rise'],
    yearsExperience: 10,
    email: generateEmail('Anna Schmidt'),
    phone: generatePhone(112),
    bio: 'Downtown specialist for German clients.',
  },
  {
    id: 'broker-113',
    name: 'Klaus Weber',
    nationality: 'German',
    gender: 'male',
    languages: ['German', 'English', 'Arabic'],
    specializations: ['Commercial', 'Business Properties'],
    yearsExperience: 15,
    email: generateEmail('Klaus Weber'),
    phone: generatePhone(113),
    bio: 'Commercial real estate advisor for German businesses.',
  },
  {
    id: 'broker-114',
    name: 'Lisa Wagner',
    nationality: 'German',
    gender: 'female',
    languages: ['German', 'English', 'French'],
    specializations: ['Palm Jumeirah', 'Waterfront'],
    yearsExperience: 8,
    email: generateEmail('Lisa Wagner'),
    phone: generatePhone(114),
    bio: 'Waterfront specialist for German families.',
  },
  {
    id: 'broker-115',
    name: 'Thomas Becker',
    nationality: 'German',
    gender: 'male',
    languages: ['German', 'English'],
    specializations: ['Marina', 'Yacht Lifestyle'],
    yearsExperience: 11,
    email: generateEmail('Thomas Becker'),
    phone: generatePhone(115),
    bio: 'Marina lifestyle specialist.',
  },
  {
    id: 'broker-116',
    name: 'Julia Fischer',
    nationality: 'German',
    gender: 'female',
    languages: ['German', 'English', 'Spanish'],
    specializations: ['Dubai Hills', 'Golf Communities'],
    yearsExperience: 6,
    email: generateEmail('Julia Fischer'),
    phone: generatePhone(116),
    bio: 'Golf community specialist for sports enthusiasts.',
  },
  {
    id: 'broker-117',
    name: 'Stefan Hoffmann',
    nationality: 'German',
    gender: 'male',
    languages: ['German', 'English'],
    specializations: ['Emirates Hills', 'Luxury Estates'],
    yearsExperience: 13,
    email: generateEmail('Stefan Hoffmann'),
    phone: generatePhone(117),
    bio: 'Ultra-luxury estate specialist.',
  },
  {
    id: 'broker-118',
    name: 'Marie Schulz',
    nationality: 'German',
    gender: 'female',
    languages: ['German', 'English', 'French'],
    specializations: ['Off-Plan', 'Investment'],
    yearsExperience: 7,
    email: generateEmail('Marie Schulz'),
    phone: generatePhone(118),
    bio: 'Off-plan investment specialist for German investors.',
  },

  // Arabic Names (10)
  {
    id: 'broker-119',
    name: 'Omar Al-Rashid',
    nationality: 'Emirati',
    gender: 'male',
    languages: ['Arabic', 'English'],
    specializations: ['Luxury Villas', 'Local Market'],
    yearsExperience: 16,
    email: generateEmail('Omar Al-Rashid'),
    phone: generatePhone(119),
    bio: 'Emirati broker with deep local market knowledge.',
  },
  {
    id: 'broker-120',
    name: 'Fatima Al-Maktoum',
    nationality: 'Emirati',
    gender: 'female',
    languages: ['Arabic', 'English', 'French'],
    specializations: ['Downtown Dubai', 'Luxury Apartments'],
    yearsExperience: 10,
    email: generateEmail('Fatima Al-Maktoum'),
    phone: generatePhone(120),
    bio: 'Downtown specialist for VIP clients.',
  },
  {
    id: 'broker-121',
    name: 'Ahmed Hassan',
    nationality: 'Egyptian',
    gender: 'male',
    languages: ['Arabic', 'English'],
    specializations: ['Palm Jumeirah', 'Waterfront'],
    yearsExperience: 12,
    email: generateEmail('Ahmed Hassan'),
    phone: generatePhone(121),
    bio: 'Waterfront specialist for Arabic-speaking clients.',
  },
  {
    id: 'broker-122',
    name: 'Layla Al-Sayed',
    nationality: 'Lebanese',
    gender: 'female',
    languages: ['Arabic', 'English', 'French'],
    specializations: ['Marina', 'Luxury Living'],
    yearsExperience: 9,
    email: generateEmail('Layla Al-Sayed'),
    phone: generatePhone(122),
    bio: 'Marina lifestyle expert for Lebanese community.',
  },
  {
    id: 'broker-123',
    name: 'Khalid Al-Farsi',
    nationality: 'Emirati',
    gender: 'male',
    languages: ['Arabic', 'English'],
    specializations: ['Emirates Hills', 'Golf Estates'],
    yearsExperience: 14,
    email: generateEmail('Khalid Al-Farsi'),
    phone: generatePhone(123),
    bio: 'Emirati specialist for ultra-luxury estates.',
  },
  {
    id: 'broker-124',
    name: 'Nadia Mansour',
    nationality: 'Jordanian',
    gender: 'female',
    languages: ['Arabic', 'English'],
    specializations: ['Dubai Hills', 'Family Homes'],
    yearsExperience: 7,
    email: generateEmail('Nadia Mansour'),
    phone: generatePhone(124),
    bio: 'Family-focused broker for Arab families.',
  },
  {
    id: 'broker-125',
    name: 'Youssef Ibrahim',
    nationality: 'Saudi',
    gender: 'male',
    languages: ['Arabic', 'English'],
    specializations: ['Investment', 'Commercial'],
    yearsExperience: 11,
    email: generateEmail('Youssef Ibrahim'),
    phone: generatePhone(125),
    bio: 'Investment advisor for GCC clients.',
  },
  {
    id: 'broker-126',
    name: 'Rania Al-Khatib',
    nationality: 'Palestinian',
    gender: 'female',
    languages: ['Arabic', 'English', 'French'],
    specializations: ['Off-Plan', 'New Developments'],
    yearsExperience: 6,
    email: generateEmail('Rania Al-Khatib'),
    phone: generatePhone(126),
    bio: 'Off-plan specialist for Arab investors.',
  },
  {
    id: 'broker-127',
    name: 'Hassan Al-Nuaimi',
    nationality: 'Emirati',
    gender: 'male',
    languages: ['Arabic', 'English'],
    specializations: ['Jumeirah', 'Beach Properties'],
    yearsExperience: 13,
    email: generateEmail('Hassan Al-Nuaimi'),
    phone: generatePhone(127),
    bio: 'Emirati beach property specialist.',
  },
  {
    id: 'broker-128',
    name: 'Sara Al-Qasimi',
    nationality: 'Emirati',
    gender: 'female',
    languages: ['Arabic', 'English', 'Spanish'],
    specializations: ['Luxury Rentals', 'VIP Services'],
    yearsExperience: 8,
    email: generateEmail('Sara Al-Qasimi'),
    phone: generatePhone(128),
    bio: 'VIP rental specialist for elite clients.',
  },
];

// Utility functions
export const getBrokerById = (id: string): Broker | undefined => {
  return allBrokers.find(broker => broker.id === id);
};

export const getBrokersByNationality = (nationality: string): Broker[] => {
  return allBrokers.filter(broker => broker.nationality === nationality);
};

export const getBrokersBySpecialization = (specialization: string): Broker[] => {
  return allBrokers.filter(broker => 
    broker.specializations.some(s => s.toLowerCase().includes(specialization.toLowerCase()))
  );
};

export const getBrokersByLanguage = (language: string): Broker[] => {
  return allBrokers.filter(broker => 
    broker.languages.some(l => l.toLowerCase() === language.toLowerCase())
  );
};
