/**
 * REVENUE OWNERSHIP RULES
 * JBJ GLOBAL REAL ESTATE | BUY · SELL · RENT
 * 
 * Global rules for revenue ownership and partner compensation.
 * ALL revenue is generated by JBJ GLOBAL REAL ESTATE.
 * Partners are compensated contractually.
 */

import type { ExecutionModel } from '@/types/revenue-attribution';

// ============================================================
// REVENUE OWNERSHIP (LOCKED - NON-NEGOTIABLE)
// ============================================================

export const REVENUE_OWNERSHIP_RULES = {
  /**
   * RULE 1: ALL revenue is generated by JBJ GLOBAL REAL ESTATE
   */
  REVENUE_OWNER: {
    entity: 'JBJ GLOBAL REAL ESTATE',
    rule: 'ALL revenue is generated by JBJ GLOBAL REAL ESTATE',
    enforcement: 'SYSTEM_LEVEL',
    exceptions: 'NONE',
  },

  /**
   * RULE 2: Partners are compensated contractually
   */
  PARTNER_COMPENSATION: {
    rule: 'Partners are compensated contractually',
    method: 'COMMISSION_FRAMEWORK',
    payment_source: 'JBJ GLOBAL REAL ESTATE',
    direct_revenue_allowed: false,
  },

  /**
   * RULE 3: No partner earns revenue directly on-platform
   */
  NO_DIRECT_EARNING: {
    rule: 'No partner ever earns revenue directly on-platform',
    enforcement: 'SYSTEM_LEVEL',
    platform_revenue_recipient: 'JBJ GLOBAL REAL ESTATE',
  },
} as const;

// ============================================================
// COMMISSION ELIGIBILITY BY EXECUTION MODEL
// ============================================================

export const COMMISSION_ELIGIBILITY_BY_MODEL: Record<ExecutionModel, {
  commission_applicable: boolean;
  origin_commission: boolean;
  execution_commission: boolean;
  notes: string;
}> = {
  A: {
    commission_applicable: true,
    origin_commission: true,
    execution_commission: false, // JBJ executes directly
    notes: 'Origin commission only - JBJ GLOBAL REAL ESTATE executes directly',
  },
  B: {
    commission_applicable: true,
    origin_commission: true,
    execution_commission: true, // Partner executes
    notes: 'Both origin and execution commission possible',
  },
  C: {
    commission_applicable: false,
    origin_commission: false,
    execution_commission: false,
    notes: 'NO COMMISSION - Intelligence only model',
  },
};

// ============================================================
// COMMISSION VISIBILITY RULES
// ============================================================

export type CommissionAccessRole = 'owner_founder' | 'executive' | 'partner' | 'internal_staff';

export const COMMISSION_VISIBILITY_BY_ROLE: Record<CommissionAccessRole, {
  view_commissions: boolean;
  view_rates: boolean;
  view_totals: boolean;
  configure_commissions: boolean;
  export_commissions: boolean;
}> = {
  owner_founder: {
    view_commissions: true,
    view_rates: true,
    view_totals: true,
    configure_commissions: true,
    export_commissions: true,
  },
  executive: {
    view_commissions: true,
    view_rates: true,
    view_totals: true,
    configure_commissions: false,
    export_commissions: false,
  },
  partner: {
    view_commissions: false,
    view_rates: false,
    view_totals: false,
    configure_commissions: false,
    export_commissions: false,
  },
  internal_staff: {
    view_commissions: false,
    view_rates: false,
    view_totals: false,
    configure_commissions: false,
    export_commissions: false,
  },
};

// ============================================================
// COMMISSION SAFEGUARDS
// ============================================================

export const COMMISSION_SAFEGUARDS = {
  /**
   * SAFEGUARD 1: No commission without Closed deal
   */
  REQUIRE_CLOSED_DEAL: {
    rule: 'Commission is calculated ONLY for Closed deals',
    required_status: 'closed',
    enforcement: 'VALIDATION_LEVEL',
  },

  /**
   * SAFEGUARD 2: No commission without valid partner record
   */
  REQUIRE_VALID_PARTNER: {
    rule: 'Commission requires valid partner record',
    partner_status_required: ['active'],
    enforcement: 'VALIDATION_LEVEL',
  },

  /**
   * SAFEGUARD 3: No commission without valid execution model
   */
  REQUIRE_VALID_MODEL: {
    rule: 'Commission requires valid execution model',
    commission_eligible_models: ['A', 'B'],
    model_c_excluded: true,
    enforcement: 'VALIDATION_LEVEL',
  },

  /**
   * SAFEGUARD 4: Commission records are read-only
   */
  RECORDS_READ_ONLY: {
    rule: 'Commission records are read-only once generated',
    immutable_after_generation: true,
    enforcement: 'SYSTEM_LEVEL',
  },

  /**
   * SAFEGUARD 5: All commissions are auditable
   */
  FULL_AUDITABILITY: {
    rule: 'All commission records are auditable',
    audit_required: true,
    linked_to_deal: true,
    enforcement: 'SYSTEM_LEVEL',
  },
} as const;

// ============================================================
// VALIDATION FUNCTIONS
// ============================================================

/**
 * Check if role can view commissions
 */
export function canViewCommissions(role: CommissionAccessRole): boolean {
  return COMMISSION_VISIBILITY_BY_ROLE[role].view_commissions;
}

/**
 * Check if role can configure commissions
 */
export function canConfigureCommissions(role: CommissionAccessRole): boolean {
  return COMMISSION_VISIBILITY_BY_ROLE[role].configure_commissions;
}

/**
 * Check if execution model is eligible for commission
 */
export function isModelEligibleForCommission(model: ExecutionModel): boolean {
  return COMMISSION_ELIGIBILITY_BY_MODEL[model].commission_applicable;
}

/**
 * Validate Model C generates NO commission
 */
export function validateModelCNoCommission(): boolean {
  return COMMISSION_ELIGIBILITY_BY_MODEL.C.commission_applicable === false;
}

/**
 * Validate partner has no commission visibility
 */
export function validatePartnerNoVisibility(): boolean {
  return COMMISSION_VISIBILITY_BY_ROLE.partner.view_commissions === false;
}

/**
 * Validate internal staff has no commission visibility
 */
export function validateInternalStaffNoVisibility(): boolean {
  return COMMISSION_VISIBILITY_BY_ROLE.internal_staff.view_commissions === false;
}

// ============================================================
// STATUS EXPORT
// ============================================================

export const REVENUE_OWNERSHIP_STATUS = {
  priority: 'P5-PART2',
  status: 'IMPLEMENTED',
  revenue_owner: 'JBJ GLOBAL REAL ESTATE',
  validations: {
    model_c_no_commission: validateModelCNoCommission(),
    partner_no_visibility: validatePartnerNoVisibility(),
    internal_staff_no_visibility: validateInternalStaffNoVisibility(),
  },
  commission_eligible_models: ['A', 'B'],
  commission_ineligible_models: ['C'],
  brand_compliance: {
    brand_name: 'JBJ GLOBAL REAL ESTATE',
    core_activities: 'BUY · SELL · RENT',
  },
} as const;
