#!/usr/bin/env python3
"""Split SECONDARY-ROUTE surface rules out of the global entry stylesheet.

Why
---
`src/index.css` still ships ~10.2k CSS rules to every visitor. Style
recalculation is therefore proportional to that rule mass on the two pages the
user actually lands on (`/` and `/properties`). Measured effect: opening a
hero filter dropdown costs ~2.4s of RecalcStyle, and pruning the guard families
at runtime drops it to ~0.4s.

Attribution rule (sound, not heuristic):
  A selector BRANCH belongs to a secondary route when it contains at least one
  SCOPE token from ROUTE_SCOPES. Those tokens are page-shell attributes that
  only ever exist in the DOM of that route, so the branch cannot match on the
  homepage / listing pages.

  A RULE is moved only when EVERY branch of its selector list carries a scope
  token from the SAME route group. Cascade order inside the extracted sheet is
  preserved, and the sheet is appended after index.css at runtime.

Usage:
  python3 scripts/qa/css_route_split.py --report
  python3 scripts/qa/css_route_split.py --apply
"""
from __future__ import annotations
import os, re, sys

sys.path.insert(0, os.path.dirname(__file__))
from cssparse import parse, serialize, Block, split_selector_list  # noqa

ENTRY = "src/index.css"
OUT = "src/styles/route-surfaces.css"

# Page-shell hooks. Every token here is rendered by exactly one secondary
# public route family (verified with ripgrep before inclusion).
ROUTE_SCOPES: dict[str, tuple[str, ...]] = {
    "careers": ("data-careers-page", "careers-open-badge", "careers-hero"),
    "insights": ("data-insights-page", "data-guide-toc", "data-guide-page"),
    "compare": (
        "data-compare-content-frame",
        "data-compare-picker",
        "data-compare-ai-ready-card",
        "data-compare-expert-card",
        "data-compare-deep-area-shell",
    ),
    "podcast": ("data-podcast-page", "data-podcast-player"),
    "aitools": ("data-ai-tools-page", "data-ai-tool-shell"),
}

CLASS_RE = re.compile(r"\.(-?[_a-zA-Z][\w-]*)")
ATTR_RE = re.compile(r"\[\s*([\w-]+)")


def branch_group(branch: str) -> str | None:
    toks = set(CLASS_RE.findall(branch))
    toks |= set(ATTR_RE.findall(branch))
    for group, scopes in ROUTE_SCOPES.items():
        if any(s in toks for s in scopes):
            return group
    return None


def main() -> None:
    apply = "--apply" in sys.argv
    text = open(ENTRY).read()
    nodes = parse(text)

    moved: list[tuple[list[str], Block, str]] = []
    stats = {"total": 0, "moved": 0}

    def walk(children, wrappers):
        for n in children:
            if not isinstance(n, Block):
                continue
            if n.at_rule:
                p = n.prelude.strip()
                if p.startswith(("@media", "@supports", "@container")):
                    walk(n.children, wrappers + [n.prelude])
                continue
            stats["total"] += 1
            branches = [b.strip() for b in split_selector_list(n.selector) if b.strip()]
            groups = {branch_group(b) for b in branches} if branches else {None}
            if len(groups) == 1 and None not in groups:
                group = groups.pop()
                n.dead = True
                stats["moved"] += 1
                moved.append((wrappers, n, group))
            else:
                walk(n.children, wrappers)

    walk(nodes, [])
    print(f"style rules scanned: {stats['total']}  route-only: {stats['moved']}")
    by_group: dict[str, int] = {}
    for _w, _r, g in moved:
        by_group[g] = by_group.get(g, 0) + 1
    for g, c in sorted(by_group.items(), key=lambda x: -x[1]):
        print(f"  {g}: {c}")
    if not moved:
        return

    chunks = [
        "/* AUTO-GENERATED by scripts/qa/css_route_split.py\n"
        "   Secondary-route surface rules (careers / insights / compare / podcast /\n"
        "   AI tools). Loaded lazily by src/components/util/RouteSurfaceStyles.tsx so\n"
        "   the homepage and listing pages never parse or retain them in the CSSOM. */\n"
    ]
    for wrappers, rule, _g in moved:
        body = f"{rule.prelude}{{{''.join(c.render() for c in rule.children)}}}"
        for w in wrappers:
            body = f"{w.strip()}{{{body}}}"
        chunks.append(body)
    out_css = "\n".join(chunks) + "\n"

    new_css = serialize(nodes)
    print(f"index.css: {len(text)} -> {len(new_css)} bytes  (-{len(text) - len(new_css)})")
    print(f"extracted: {len(out_css)} bytes")

    if apply:
        os.makedirs(os.path.dirname(OUT), exist_ok=True)
        open(OUT, "w").write(out_css)
        open(ENTRY, "w").write(new_css)
        print("applied.")
    else:
        open("/tmp/route-surfaces.preview.css", "w").write(out_css)
        print("dry run -> /tmp/route-surfaces.preview.css")


if __name__ == "__main__":
    main()
