"""Generator for src/styles/theme-moon.css (MOON / night theme inversion layer).

Run:  python3 scripts/qa/gen_theme_moon.py

Why a generator: index.css carries 225+ champagne rules written as
`html body #root … { background:#F7F2EA !important }`. To beat every one of them
without touching them, each moon selector needs a very high-specificity scope.
The scope repeats the theme attribute on <html> 8x and includes `#root`.
The `:not([data-jbj-backend-lock="1"])` guard keeps the OWNER back-office routes
on their fixed emerald CRM skin.
"""
HTML = "html" + '[data-jbj-theme="moon"]' * 8 + ':not([data-jbj-backend-lock="1"])'
SCOPE = f"{HTML} body #root"

CHAMPAGNE = ["#FDFBF7", "#FFFDF9", "#F7F2EA", "#F2EBDC", "#EFE6D6", "#FAF7F0", "#F5F0E6", "#FFFFFF"]
GOLD = ["#B89555", "#D4AF37", "#C9A961", "#EFE6D6"]
DARK_INK = ["#1A1A1A", "#0A0A0A", "#111827", "#0F172A", "#000000", "#064E3B", "#042c1c"]

# Elements that must keep their own colours in Moon mode.
KEEP = (
    ':not([data-jbj-theme-exempt])'
    ':not([class*="bg-clip-text"])'
    ':not([class*="text-transparent"])'
    ':not([class*="text-[#B89555]"])'
    ':not([class*="text-[#D4AF37]"])'
    ':not([class*="text-[#C9A961]"])'
    ':not(img):not(svg):not(path):not(video):not(canvas)'
)


def sel(parts, scope=SCOPE):
    return ",\n".join(f"{scope} {p}" for p in parts)


out = [f"""/* GENERATED by scripts/qa/gen_theme_moon.py — do not hand-edit.
 *
 * MOON (night) theme. Loaded lazily by ThemeModeContext only while Moon mode is
 * active, so Sun-mode visitors never pay its style-recalculation cost.
 *
 *   PRIMARY   = emerald -> black pair gradient (#064E3B -> #042c1c -> #000)
 *   CONTENT   = PURE WHITE text and icons on every emerald surface
 *   SECONDARY = champagne/gold, ALWAYS with black ink and black icons on top
 */

:root {{
  --jbj-moon-pair: linear-gradient(160deg, #064E3B 0%, #042c1c 55%, #000000 100%);
  --jbj-moon-surface: #06231A;
  --jbj-moon-surface-raised: #082D21;
  --jbj-moon-hairline: rgba(255, 255, 255, 0.14);
}}

/* 1. Semantic tokens */
{HTML} {{
  --background: 160 62% 8%;
  --foreground: 0 0% 100%;
  --card: 160 55% 10%;
  --card-foreground: 0 0% 100%;
  --popover: 160 55% 10%;
  --popover-foreground: 0 0% 100%;
  --primary: 162 85% 16%;
  --primary-foreground: 0 0% 100%;
  --secondary: 38 39% 53%;
  --secondary-foreground: 0 0% 6%;
  --muted: 160 30% 14%;
  --muted-foreground: 0 0% 82%;
  --accent: 38 39% 53%;
  --accent-foreground: 0 0% 6%;
  --border: 160 25% 20%;
  --input: 160 25% 20%;
  --ring: 38 39% 53%;
  color-scheme: dark;
}}

/* 2. Page canvas */
{HTML}, {HTML} body {{
  background: #04150F !important;
  background-image: none !important;
  color: #FFFFFF;
}}
"""]

# 3. Champagne surfaces -> emerald pair gradient
surfaces = []
for t in CHAMPAGNE:
    surfaces += [f'[class*="bg-[{t}]"]', f'[class*="from-[{t}]"]', f'[class*="via-[{t}]"]',
                 f'[class*="to-[{t}]"]', f'[style*="{t}"]', f'[style*="{t.lower()}"]']
surfaces += ['[class~="bg-white"]', '.jj-main-shell', '.jj-utility-shell', '.jj-champagne-surface',
             '[data-chrome="sidebar"] > *', '[data-chrome="sidebar"] > * > *',
             '[data-sidebar-emerald]']
out.append(f"""/* 3. Champagne surfaces -> emerald pair gradient */
{sel(surfaces)} {{
  background-color: var(--jbj-moon-surface) !important;
  background-image: var(--jbj-moon-pair) !important;
}}
""")

# 4. Universal ink inversion -> pure white
out.append(f"""/* 4. Ink inversion: everything reads PURE WHITE unless it opts out or sits on
      a champagne surface (rule 6 restores black ink there). */
{SCOPE} {KEEP} {{
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
}}
{SCOPE} .lucide {{
  color: #FFFFFF !important;
  stroke: #FFFFFF !important;
}}
""")

# 5. Hairlines
borders = [f'[class*="border-[{t}]"]' for t in CHAMPAGNE] + ['[class*="border-[#E5E7EB]"]', '[class~="border-border"]']
out.append(f"""/* 5. Hairlines */
{sel(borders)} {{
  border-color: var(--jbj-moon-hairline) !important;
}}
""")

# 6. Champagne accent keeps its colour with BLACK ink (Contrast Guard)
gold_parts = [f'[class*="bg-[{t}]"]' for t in GOLD] + ['[data-surface="champagne"]', '[data-jbj-surface="champagne"]']
out.append(f"""/* 6. Champagne / gold accent surfaces — always BLACK ink and BLACK icons */
{sel(gold_parts)},
{sel([p + " *" for p in gold_parts])} {{
  color: #0A0A0A !important;
  -webkit-text-fill-color: #0A0A0A !important;
}}
{sel([p + " .lucide" for p in gold_parts])} {{
  color: #0A0A0A !important;
  stroke: #0A0A0A !important;
}}
""")

# 7. Form controls
out.append(f"""/* 7. Form controls */
{sel(["input", "select", "textarea"])} {{
  background-color: var(--jbj-moon-surface-raised) !important;
  background-image: none !important;
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
  border-color: var(--jbj-moon-hairline) !important;
}}
{sel(["input::placeholder", "textarea::placeholder"])} {{
  color: rgba(255, 255, 255, 0.55) !important;
  -webkit-text-fill-color: rgba(255, 255, 255, 0.55) !important;
}}
""")

# 8. Floating layers
floats = ['[role="menu"]', '[role="listbox"]', '[role="dialog"]', "[data-radix-popper-content-wrapper] > *"]
out.append(f"""/* 8. Floating layers (menus, dialogs, popovers) */
{sel(floats, HTML + " body")} {{
  background-color: var(--jbj-moon-surface) !important;
  background-image: var(--jbj-moon-pair) !important;
  border-color: var(--jbj-moon-hairline) !important;
}}
{sel([p + " " + KEEP for p in floats], HTML + " body")} {{
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
}}
""")

# 9. Emerald surfaces + media
out.append(f"""/* 9. Emerald surfaces keep white ink; media is never re-tinted */
{sel(['[data-surface="emerald"]', '[data-surface="emerald"] ' + KEEP,
      '[data-jbj-surface="emerald"]', '[data-jbj-surface="emerald"] ' + KEEP])} {{
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
}}
{sel(["img", "video", "canvas", "picture", "[data-developer-logo-plate]", "[data-jbj-theme-exempt]"])} {{
  background-image: none !important;
}}
""")

# 10. Gradient-clipped labels (background-clip:text) would vanish on an emerald
# surface, so in Moon mode they render as solid white ink instead.
out.append(f"""/* 10. Clipped-gradient labels -> solid white ink */
{sel(['[data-sidebar-section-label]', '[data-sidebar-subitem-label]',
      '[data-surface="emerald"] [class*="bg-clip-text"]',
      '[data-sidebar-emerald] [class*="bg-clip-text"]'])} {{
  background-image: none !important;
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
}}
""")

with open("src/styles/theme-moon.css", "w") as fh:
    fh.write("\n".join(out))
print("wrote src/styles/theme-moon.css")
