"""Generate the semantic JBJ Hub-inspired public Moon skin."""

CSS = r'''/* GENERATED by scripts/qa/gen_theme_moon.py — do not hand-edit. */
:root {
  --jbj-moon-chrome: linear-gradient(180deg, #064E3B 0%, #032A1E 44%, #000000 100%);
  --jbj-moon-chrome-h: linear-gradient(90deg, #064E3B 0%, #032A1E 52%, #000000 100%);
  --jbj-moon-action: linear-gradient(135deg, #064E3B 0%, #042C1C 58%, #000000 100%);
  --jbj-moon-canvas: #F5F7F6;
  --jbj-moon-pearl: #FFFFFF;
  --jbj-moon-mint: #EAF4EF;
  --jbj-moon-ink: #17231F;
  --jbj-moon-muted: #52635C;
  --jbj-moon-line: #D8E4DE;
  --jbj-moon-chrome-line: rgba(255,255,255,.18);
}

html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) {
  --background: 150 12% 96%;
  --foreground: 157 20% 11%;
  --card: 0 0% 100%;
  --card-foreground: 157 20% 11%;
  --popover: 0 0% 100%;
  --popover-foreground: 157 20% 11%;
  --primary: 162 85% 16%;
  --primary-foreground: 0 0% 100%;
  --secondary: 150 32% 94%;
  --secondary-foreground: 157 20% 11%;
  --muted: 150 20% 92%;
  --muted-foreground: 153 10% 36%;
  --accent: 150 32% 94%;
  --accent-foreground: 157 20% 11%;
  --border: 150 18% 87%;
  --input: 150 18% 87%;
  --ring: 162 85% 16%;
  --jj-seg-hairline: rgba(6,78,59,.25);
  --jj-panel-hairline: rgba(6,78,59,.20);
  color-scheme: light;
}

html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]),
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body,
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root,
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root main.jj-main-shell {
  background: var(--jbj-moon-canvas) !important;
  background-image: none !important;
  color: var(--jbj-moon-ink) !important;
}

/* Desktop public chrome mirrors the JBJ Hub. */
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="sidebar"] [data-sidebar-emerald] {
  background: var(--jbj-moon-chrome) !important;
  background-image: var(--jbj-moon-chrome) !important;
  color: #FFFFFF !important;
  padding-inline: 14px !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="sidebar"] > div > div > div {
  background: var(--jbj-moon-chrome) !important;
  background-image: var(--jbj-moon-chrome) !important;
  border-color: var(--jbj-moon-chrome-line) !important;
  box-shadow: none !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="sidebar"] [data-sidebar-emerald] > div:first-child,
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-jj-utility-bar] {
  background: var(--jbj-moon-chrome-h) !important;
  background-image: var(--jbj-moon-chrome-h) !important;
  border-color: var(--jbj-moon-chrome-line) !important;
  box-shadow: none !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="sidebar"] [data-sidebar-emerald] :is(a,button),
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="sidebar"] [data-sidebar-emerald] :is(span,p,label),
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-jj-utility-bar] :is(button,a,span),
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-jj-utility-bar] :is(svg,path) {
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
  stroke: currentColor !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="sidebar"] [data-sidebar-emerald] :is(a,button):not([data-active="true"]):not([aria-current="page"]) {
  background: transparent !important;
  background-image: none !important;
  border-color: transparent !important;
  box-shadow: none !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="sidebar"] [data-sidebar-emerald] :is(a,button)[data-active="true"],
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="sidebar"] [data-sidebar-emerald] a[aria-current="page"] {
  background: rgba(255,255,255,.20) !important;
  background-image: none !important;
  border-color: rgba(255,255,255,.12) !important;
}

/* Mobile chrome and drawer use the same Hub language. */
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="header"] header {
  background: var(--jbj-moon-chrome-h) !important;
  background-image: var(--jbj-moon-chrome-h) !important;
  border-color: var(--jbj-moon-chrome-line) !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-chrome="header"] :is(.jj-header-wordmark,.jj-header-tagline,.jj-hamburger,.jj-hamburger-close,.jj-hamburger-bar) {
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
  background-color: #FFFFFF !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-jj-mobile-drawer] {
  background: var(--jbj-moon-chrome) !important;
  background-image: var(--jbj-moon-chrome) !important;
  padding-inline: 14px !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-jj-mobile-drawer] :is(a,button,p,span),
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-jj-mobile-drawer] :is(svg,path) {
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
  stroke: currentColor !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-jj-mobile-drawer] :is(a,button):not([aria-current="page"]) {
  background: transparent !important;
  border-color: transparent !important;
  box-shadow: none !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-jj-mobile-drawer] a[aria-current="page"] {
  background: rgba(255,255,255,.20) !important;
  border-color: rgba(255,255,255,.14) !important;
}

/* Public Moon content is CRM pearl/mint, never a wall of emerald. */
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root :is(section,article)[data-jbj-invert="pair"],
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root :is(section,article)[data-surface="emerald"],
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root :is(.jj-emerald-card,.jj-champagne-surface):not(button):not(a) {
  background: var(--jbj-moon-pearl) !important;
  background-image: none !important;
  color: var(--jbj-moon-ink) !important;
  border-color: var(--jbj-moon-line) !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root :is(section,article)[data-jbj-invert="pair"] :is(h1,h2,h3,h4,h5,h6,p,span,a,label,li),
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root :is(section,article)[data-surface="emerald"] :is(h1,h2,h3,h4,h5,h6,p,span,a,label,li) {
  color: var(--jbj-moon-ink) !important;
  -webkit-text-fill-color: var(--jbj-moon-ink) !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root :is(button,a,[role="button"])[data-surface="emerald"],
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root :is(.jj-emerald-action,.jj-cta-emerald,.jj-cta-primary) {
  background: var(--jbj-moon-action) !important;
  background-image: var(--jbj-moon-action) !important;
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
  border-color: rgba(255,255,255,.18) !important;
}

/* Menus and search filters remain crisp pearl with graphite ink. */
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body :is([role="menu"],[role="listbox"],[data-search-dropdown],[data-radix-popper-content-wrapper] > *) {
  background: var(--jbj-moon-pearl) !important;
  background-image: none !important;
  color: var(--jbj-moon-ink) !important;
  border-color: var(--jbj-moon-line) !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body [data-search-dropdown] :is(input,button,span,p) {
  color: var(--jbj-moon-ink) !important;
  -webkit-text-fill-color: var(--jbj-moon-ink) !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body [data-search-dropdown] [aria-pressed="true"],
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body [data-search-dropdown] [aria-pressed="true"] * {
  color: #FFFFFF !important;
  -webkit-text-fill-color: #FFFFFF !important;
}

/* Partner strip flips from Sun emerald to a clean pearl CRM band. */
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-partners-marquee] {
  background: var(--jbj-moon-pearl) !important;
  background-image: none !important;
  border-block: 1px solid var(--jbj-moon-line) !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root [data-partners-heading] p {
  color: var(--jbj-moon-ink) !important;
  -webkit-text-fill-color: var(--jbj-moon-ink) !important;
}
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root .jj-partner-mark img { filter: brightness(0) !important; }

/* Emerald chrome never receives champagne/gold borders. */
html[data-jbj-theme="moon"]:not([data-jbj-backend-lock="1"]) body #root :is([data-chrome="sidebar"],[data-jj-utility-bar],[data-chrome="header"],[data-jj-mobile-drawer]) * {
  --jj-seg-hairline: rgba(255,255,255,.28);
  --jj-panel-hairline: rgba(255,255,255,.20);
}
'''

with open("src/styles/theme-moon.css", "w", encoding="utf-8") as fh:
    fh.write(CSS)
print("wrote src/styles/theme-moon.css")