ALTER TABLE public.portal_listings
  ADD COLUMN IF NOT EXISTS unit_number text,
  ADD COLUMN IF NOT EXISTS plot_size_sqft numeric,
  ADD COLUMN IF NOT EXISTS view text,
  ADD COLUMN IF NOT EXISTS floor text,
  ADD COLUMN IF NOT EXISTS parking integer,
  ADD COLUMN IF NOT EXISTS property_age integer,
  ADD COLUMN IF NOT EXISTS availability_date date,
  ADD COLUMN IF NOT EXISTS current_rent numeric,
  ADD COLUMN IF NOT EXISTS min_acceptable_price numeric,
  ADD COLUMN IF NOT EXISTS purchase_price numeric,
  ADD COLUMN IF NOT EXISTS service_charge numeric,
  ADD COLUMN IF NOT EXISTS is_mortgaged boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS mortgage_bank text,
  ADD COLUMN IF NOT EXISTS rera_permit text,
  ADD COLUMN IF NOT EXISTS cover_image_url text,
  ADD COLUMN IF NOT EXISTS video_url text,
  ADD COLUMN IF NOT EXISTS tour_url text,
  ADD COLUMN IF NOT EXISTS dld_consent_at timestamptz,
  ADD COLUMN IF NOT EXISTS tnc_consent_at timestamptz;