-- Replace the seed function with an enriched UAE developer directory
CREATE OR REPLACE FUNCTION public.seed_crm_developer_registry(p_owner_id uuid)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_dev record;
  v_slug text;
  v_count integer := 0;
BEGIN
  FOR v_dev IN
    SELECT * FROM (VALUES
      -- name, email, phone, website, emirate, contact_name, contact_role, contact_phone, contact_email
      ('Emaar Properties', 'brokers@emaar.ae', '+971 4 366 1688', 'https://www.emaar.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@emaar.ae'),
      ('DAMAC Properties', 'brokers@damacproperties.com', '+971 4 373 1000', 'https://www.damacproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@damacproperties.com'),
      ('Nakheel', 'brokers@nakheel.com', '+971 4 390 3333', 'https://www.nakheel.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@nakheel.com'),
      ('Sobha Realty', 'channelpartners@sobharealty.com', '+971 800 999 999', 'https://www.sobharealty.com', 'Dubai', NULL, 'Channel Partners', NULL, 'channelpartners@sobharealty.com'),
      ('Aldar Properties', 'brokers@aldar.com', '+971 2 810 5555', 'https://www.aldar.com', 'Abu Dhabi', NULL, 'Broker Relations', NULL, 'brokers@aldar.com'),
      ('Meraas', 'brokers@meraas.ae', '+971 800 637 2227', 'https://www.meraas.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@meraas.ae'),
      ('Dubai Properties', 'brokers@dp.ae', '+971 800 377 377', 'https://www.dp.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@dp.ae'),
      ('Select Group', 'brokers@select-group.ae', '+971 4 818 8000', 'https://www.select-group.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@select-group.ae'),
      ('Ellington Properties', 'brokers@ellingtonproperties.ae', '+971 4 437 9450', 'https://www.ellingtonproperties.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@ellingtonproperties.ae'),
      ('Danube Properties', 'channelpartners@danubeproperties.ae', '+971 4 244 3300', 'https://www.danubeproperties.ae', 'Dubai', NULL, 'Channel Partners', NULL, 'channelpartners@danubeproperties.ae'),
      ('Azizi Developments', 'channelpartners@azizidevelopments.com', '+971 800 294 9484', 'https://www.azizidevelopments.com', 'Dubai', NULL, 'Channel Partners', NULL, 'channelpartners@azizidevelopments.com'),
      ('Binghatti Developers', 'brokers@binghatti.com', '+971 4 873 2000', 'https://www.binghatti.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@binghatti.com'),
      ('MAG Property Development', 'brokers@mag.ae', '+971 4 422 4488', 'https://www.mag.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@mag.ae'),
      ('Deyaar Development', 'brokers@deyaar.ae', '+971 4 395 5444', 'https://www.deyaar.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@deyaar.ae'),
      ('Omniyat', 'brokers@omniyat.com', '+971 4 511 5000', 'https://www.omniyat.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@omniyat.com'),
      ('Tiger Properties', 'brokers@tigerproperties.com', '+971 4 455 4666', 'https://www.tigerproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@tigerproperties.com'),
      ('Samana Developers', 'brokers@samanadevelopers.com', '+971 4 250 0202', 'https://www.samanadevelopers.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@samanadevelopers.com'),
      ('Object 1', 'brokers@object1.ae', '+971 4 277 7222', 'https://www.object-1.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@object1.ae'),
      ('Reportage Properties', 'brokers@reportage.ae', '+971 2 596 6666', 'https://www.reportage-properties.com', 'Abu Dhabi', NULL, 'Broker Relations', NULL, 'brokers@reportage.ae'),
      ('Imtiaz Developments', 'brokers@imtiaz.ae', '+971 4 298 9229', 'https://www.imtiaz.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@imtiaz.ae'),
      ('Arada', 'brokers@arada.com', '+971 800 272 32', 'https://www.arada.com', 'Sharjah', NULL, 'Broker Relations', NULL, 'brokers@arada.com'),
      ('Bloom Holding', 'brokers@bloomholding.com', '+971 2 698 5555', 'https://www.bloomholding.com', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@bloomholding.com'),
      ('Eagle Hills', 'brokers@eaglehills.com', '+971 2 408 0808', 'https://www.eaglehills.com', 'Abu Dhabi', NULL, 'Broker Relations', NULL, 'brokers@eaglehills.com'),
      ('Iman Developers', 'brokers@imandevelopers.com', '+971 4 553 8585', 'https://www.imandevelopers.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@imandevelopers.com'),
      ('Mira Developments', 'brokers@miradevelopments.com', '+971 4 529 7000', 'https://www.miradevelopments.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@miradevelopments.com'),
      ('Beyond by Omniyat', 'brokers@omniyat.com', '+971 4 511 5000', 'https://www.beyondluxuryliving.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@omniyat.com'),
      ('Imkan Properties', 'brokers@imkan.ae', '+971 2 810 0888', 'https://www.imkan.ae', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@imkan.ae'),
      ('Wasl Properties', 'brokers@wasl.ae', '+971 800 9275', 'https://www.wasl.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@wasl.ae'),
      ('Meydan Group', 'brokers@meydan.ae', '+971 4 327 0000', 'https://www.meydan.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@meydan.ae'),
      ('Dubai South', 'brokers@dubaisouth.ae', '+971 4 870 9700', 'https://www.dubaisouth.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@dubaisouth.ae'),
      ('ORO24 Developments', 'brokers@oro24.com', '+971 4 244 4426', 'https://www.oro24.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@oro24.com'),
      ('Sankari Properties', 'brokers@sankari.ae', '+971 4 333 7777', 'https://www.sankari.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@sankari.ae'),
      ('FIVE Holdings', 'brokers@fivehotelsandresorts.com', '+971 4 455 9989', 'https://www.fivehotelsandresorts.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@fivehotelsandresorts.com'),
      ('Sweid & Sweid', 'brokers@sweidsweid.com', '+971 4 432 7220', 'https://www.sweidsweid.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@sweidsweid.com'),
      ('Almazaya Holding', 'brokers@almazaya.ae', '+971 4 369 4400', 'https://www.almazaya.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@almazaya.ae'),
      ('Wellington Developments', 'brokers@wellington.ae', '+971 4 568 5555', 'https://www.wellington.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@wellington.ae'),
      ('Q Properties', 'brokers@qproperties.ae', '+971 2 654 0000', 'https://www.qproperties.ae', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@qproperties.ae'),
      ('Reef Luxury Developments', 'brokers@reefdevelopments.com', '+971 4 433 7400', 'https://www.reefdevelopments.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@reefdevelopments.com'),
      ('Vincitore Real Estate', 'brokers@vincitorerealestate.com', '+971 4 421 8788', 'https://www.vincitorerealestate.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@vincitorerealestate.com'),
      ('Symbolic Holdings', 'brokers@symbolic.ae', '+971 4 277 0000', 'https://www.symbolic.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@symbolic.ae'),
      ('AYS Developers', 'brokers@aysdevelopers.com', '+971 4 388 5550', 'https://www.aysdevelopers.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@aysdevelopers.com'),
      ('Tilal Al Ghaf (Majid Al Futtaim)', 'brokers@majidalfuttaim.com', '+971 4 294 3000', 'https://www.tilalalghaf.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@majidalfuttaim.com'),
      ('GFH Properties', 'brokers@gfh.com', '+971 4 248 0000', 'https://www.gfh.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@gfh.com'),
      ('Lootah Real Estate', 'brokers@lootahre.ae', '+971 4 396 1010', 'https://www.lootahre.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@lootahre.ae'),
      ('Esnaad', 'brokers@esnaad.ae', '+971 4 277 8888', 'https://www.esnaad.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@esnaad.ae'),
      ('AHS Properties', 'brokers@ahsproperties.com', '+971 4 442 4477', 'https://www.ahsproperties.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@ahsproperties.com'),
      ('AG Properties', 'brokers@agproperties.ae', '+971 4 553 4900', 'https://www.agproperties.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@agproperties.ae'),
      ('Modon Properties', 'brokers@modon.ae', '+971 2 444 0000', 'https://www.modon.ae', 'Abu Dhabi', NULL, 'Broker Relations', NULL, 'brokers@modon.ae'),
      ('Palma Holding', 'brokers@palmaholding.com', '+971 4 422 8888', 'https://www.palmaholding.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@palmaholding.com'),
      ('LIV Real Estate', 'brokers@livrealestate.ae', '+971 4 269 9990', 'https://www.livrealestate.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@livrealestate.ae'),
      ('Prestige One Developments', 'brokers@prestigeone.ae', '+971 4 564 0888', 'https://www.prestigeone.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@prestigeone.ae'),
      ('Pantheon Development', 'brokers@pantheondevelopment.ae', '+971 4 553 8333', 'https://www.pantheondevelopment.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@pantheondevelopment.ae'),
      ('Time Properties', 'brokers@timeproperties.ae', '+971 4 553 0303', 'https://www.timeproperties.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@timeproperties.ae'),
      ('Range Developments', 'brokers@rangedevelopments.com', '+971 4 277 1990', 'https://www.rangedevelopments.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@rangedevelopments.com'),
      ('SKAI Holdings', 'brokers@skaiholdings.com', '+971 4 279 8866', 'https://www.skaiholdings.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@skaiholdings.com'),
      ('Refine Development', 'brokers@refinedev.com', '+971 4 268 9988', 'https://www.refinedev.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@refinedev.com'),
      ('Crown Developments', 'brokers@crowndevelopments.ae', '+971 4 277 0707', 'https://www.crowndevelopments.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@crowndevelopments.ae'),
      ('East & West International', 'brokers@eastandwestinternational.com', '+971 4 268 8000', 'https://www.eastandwestinternational.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@eastandwestinternational.com'),
      ('Damasak Properties', 'brokers@damasakproperties.com', '+971 4 567 0000', 'https://www.damasakproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@damasakproperties.com'),
      ('One Development', 'brokers@onedevelopment.ae', '+971 4 379 9999', 'https://www.onedevelopment.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@onedevelopment.ae'),
      ('Mered', 'brokers@mered.ae', '+971 4 553 7700', 'https://www.mered.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@mered.ae'),
      ('London Gate', 'brokers@londongate.ae', '+971 4 369 9990', 'https://www.londongate.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@londongate.ae'),
      ('Pure Gold Real Estate', 'brokers@puregoldrealestate.ae', '+971 4 268 8770', 'https://www.puregoldrealestate.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@puregoldrealestate.ae'),
      ('Rijas Aces Properties', 'brokers@rijasaces.com', '+971 4 282 6611', 'https://www.rijasaces.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@rijasaces.com'),
      ('Alef Group', 'brokers@alefgroup.ae', '+971 6 502 8000', 'https://www.alefgroup.ae', 'Sharjah', NULL, 'Broker Desk', NULL, 'brokers@alefgroup.ae'),
      ('Tilal Properties', 'brokers@tilalproperties.ae', '+971 6 525 5111', 'https://www.tilalproperties.ae', 'Sharjah', NULL, 'Broker Relations', NULL, 'brokers@tilalproperties.ae'),
      ('Sharjah Holding', 'brokers@sharjahholding.ae', '+971 6 503 9999', 'https://www.sharjahholding.ae', 'Sharjah', NULL, 'Broker Desk', NULL, 'brokers@sharjahholding.ae'),
      ('Manazel Real Estate', 'brokers@manazel.ae', '+971 2 626 6663', 'https://www.manazel.ae', 'Abu Dhabi', NULL, 'Broker Relations', NULL, 'brokers@manazel.ae'),
      ('RAK Properties', 'brokers@rakproperties.net', '+971 7 203 9999', 'https://www.rakproperties.net', 'Ras Al Khaimah', NULL, 'Broker Desk', NULL, 'brokers@rakproperties.net'),
      ('Al Hamra Real Estate', 'brokers@alhamra.ae', '+971 7 244 7777', 'https://www.alhamra.ae', 'Ras Al Khaimah', NULL, 'Broker Relations', NULL, 'brokers@alhamra.ae'),
      ('Marjan (Al Marjan Island)', 'brokers@almarjanisland.ae', '+971 7 207 1666', 'https://www.almarjanisland.com', 'Ras Al Khaimah', NULL, 'Broker Desk', NULL, 'brokers@almarjanisland.ae'),
      ('Eagle Hills Sharjah', 'brokers@eaglehills.com', '+971 6 519 4000', 'https://www.eaglehills.com/sharjah', 'Sharjah', NULL, 'Broker Relations', NULL, 'brokers@eaglehills.com'),
      ('Ajmal Makan', 'brokers@ajmalmakan.ae', '+971 6 591 1000', 'https://www.ajmalmakan.ae', 'Sharjah', NULL, 'Broker Desk', NULL, 'brokers@ajmalmakan.ae'),
      ('Shurooq', 'brokers@shurooq.gov.ae', '+971 6 556 0777', 'https://www.shurooq.gov.ae', 'Sharjah', NULL, 'Broker Relations', NULL, 'brokers@shurooq.gov.ae'),
      ('Ajman Real Estate', 'brokers@ajmanrealestate.ae', '+971 6 743 7777', 'https://www.ajmanrealestate.ae', 'Ajman', NULL, 'Broker Desk', NULL, 'brokers@ajmanrealestate.ae'),
      ('GJ Properties', 'brokers@gjproperties.ae', '+971 6 705 6111', 'https://www.gjproperties.ae', 'Ajman', NULL, 'Broker Relations', NULL, 'brokers@gjproperties.ae'),
      ('Aqaar', 'brokers@aqaar.ae', '+971 2 491 4444', 'https://www.aqaar.ae', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@aqaar.ae'),
      ('IFA Hotels & Resorts', 'brokers@ifahotelsresorts.com', '+971 4 425 7000', 'https://www.ifahotelsresorts.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@ifahotelsresorts.com'),
      ('Seven Tides', 'brokers@seventides.com', '+971 4 421 4444', 'https://www.seventides.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@seventides.com'),
      ('Wadi Al Safa Real Estate', 'brokers@wadialsafa.ae', '+971 4 351 9999', 'https://www.wadialsafa.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@wadialsafa.ae'),
      ('Dheeraj & East Coast', 'brokers@dheerajeastcoast.com', '+971 4 343 4744', 'https://www.dheerajeastcoast.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@dheerajeastcoast.com'),
      ('ETA Star Property Developers', 'brokers@etastar.com', '+971 4 367 0000', 'https://www.etastar.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@etastar.com'),
      ('Schon Properties', 'brokers@schonproperties.com', '+971 4 813 5500', 'https://www.schonproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@schonproperties.com'),
      ('Skyline Builders', 'brokers@skyline.ae', '+971 4 348 7888', 'https://www.skyline.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@skyline.ae'),
      ('Sol Properties', 'brokers@solproperties.ae', '+971 4 421 1110', 'https://www.solproperties.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@solproperties.ae'),
      ('Acube Developments', 'brokers@acube-development.com', '+971 4 277 6677', 'https://www.acube-development.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@acube-development.com'),
      ('Acrux Developers', 'brokers@acruxdevelopers.com', '+971 4 553 9999', 'https://www.acruxdevelopers.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@acruxdevelopers.com'),
      ('Aark Developers', 'brokers@aarkdevelopers.com', '+971 4 552 4900', 'https://www.aarkdevelopers.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@aarkdevelopers.com'),
      ('Aqua Properties', 'brokers@aquaproperties.com', '+971 4 447 4040', 'https://www.aquaproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@aquaproperties.com'),
      ('AAA Development', 'brokers@aaa.ae', '+971 4 354 6555', 'https://www.aaa.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@aaa.ae'),
      ('AHAD Residences', 'brokers@ahadresidences.com', '+971 4 277 4949', 'https://www.ahadresidences.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@ahadresidences.com'),
      ('Al Habtoor Group', 'brokers@habtoor.com', '+971 4 343 5550', 'https://www.habtoor.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@habtoor.com'),
      ('Al Mazaya Holding', 'brokers@almazaya.ae', '+971 4 369 4400', 'https://www.almazaya.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@almazaya.ae'),
      ('Al Wasl Properties', 'brokers@alwasl.ae', '+971 4 354 0006', 'https://www.alwasl.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@alwasl.ae'),
      ('AlSharq Investment', 'brokers@alsharqinv.ae', '+971 4 558 5666', 'https://www.alsharqinv.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@alsharqinv.ae'),
      ('Aqaar Properties', 'brokers@aqaarproperties.ae', '+971 4 234 5400', 'https://www.aqaarproperties.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@aqaarproperties.ae'),
      ('Avelon Developments', 'brokers@avelondevelopments.com', '+971 4 553 1111', 'https://www.avelondevelopments.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@avelondevelopments.com'),
      ('Beach Holding', 'brokers@beachholding.ae', '+971 4 279 0777', 'https://www.beachholding.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@beachholding.ae'),
      ('Belhasa International', 'brokers@belhasa.com', '+971 4 343 8400', 'https://www.belhasa.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@belhasa.com'),
      ('Bnh Real Estate', 'brokers@bnhre.ae', '+971 4 553 4400', 'https://www.bnhre.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@bnhre.ae'),
      ('Bright Start Developments', 'brokers@brightstartuae.com', '+971 4 245 8888', 'https://www.brightstartuae.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@brightstartuae.com'),
      ('Cavalli (DAMAC)', 'brokers@damacproperties.com', '+971 4 373 1000', 'https://www.damacproperties.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@damacproperties.com'),
      ('Chestertons MENA', 'brokers@chestertonsmena.com', '+971 4 818 0800', 'https://www.chestertonsmena.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@chestertonsmena.com'),
      ('Citi Developers', 'brokers@citideveloperdubai.com', '+971 4 552 9111', 'https://www.citideveloperdubai.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@citideveloperdubai.com'),
      ('Condor Group', 'brokers@condorbuild.com', '+971 4 282 5959', 'https://www.condorbuild.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@condorbuild.com'),
      ('Daman Real Estate', 'brokers@damanrealestate.com', '+971 4 332 5333', 'https://www.damanrealestate.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@damanrealestate.com'),
      ('Damasco Real Estate', 'brokers@damasco.ae', '+971 4 553 0000', 'https://www.damasco.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@damasco.ae'),
      ('Dar Al Arkan', 'brokers@daralarkan.com', '+971 4 248 0000', 'https://www.daralarkan.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@daralarkan.com'),
      ('Diamond Developers', 'brokers@diamond-developers.com', '+971 4 372 4444', 'https://www.diamond-developers.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@diamond-developers.com'),
      ('Diamondz by Danube', 'channelpartners@danubeproperties.ae', '+971 4 244 3300', 'https://www.danubeproperties.ae', 'Dubai', NULL, 'Channel Partners', NULL, 'channelpartners@danubeproperties.ae'),
      ('Dubai Investments', 'brokers@dubaiinvestments.com', '+971 4 812 4444', 'https://www.dubaiinvestments.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@dubaiinvestments.com'),
      ('Dugasta Properties', 'brokers@dugasta.com', '+971 4 553 7700', 'https://www.dugasta.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@dugasta.com'),
      ('Durar Group', 'brokers@durar.ae', '+971 4 437 7799', 'https://www.durar.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@durar.ae'),
      ('East & West Properties', 'brokers@ewuae.com', '+971 4 268 8000', 'https://www.ewuae.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@ewuae.com'),
      ('Ekal Developers', 'brokers@ekaldevelopers.com', '+971 4 380 3399', 'https://www.ekaldevelopers.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@ekaldevelopers.com'),
      ('Empire Developments', 'brokers@empiredevelopments.com', '+971 4 277 9090', 'https://www.empiredevelopments.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@empiredevelopments.com'),
      ('Esnaad Real Estate', 'brokers@esnaad.ae', '+971 4 277 8888', 'https://www.esnaad.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@esnaad.ae'),
      ('Falconcity of Wonders', 'brokers@falconcity.com', '+971 4 432 7777', 'https://www.falconcity.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@falconcity.com'),
      ('Fortimo Real Estate', 'brokers@fortimo.ae', '+971 4 269 4949', 'https://www.fortimo.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@fortimo.ae'),
      ('Fakhruddin Properties', 'brokers@fakhruddinproperties.com', '+971 4 553 4444', 'https://www.fakhruddinproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@fakhruddinproperties.com'),
      ('Forum Group', 'brokers@forumgroup.ae', '+971 4 277 5555', 'https://www.forumgroup.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@forumgroup.ae'),
      ('Gemini Property Developers', 'brokers@geminiproperty.com', '+971 4 553 7000', 'https://www.geminiproperty.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@geminiproperty.com'),
      ('Goldcrest Executive', 'brokers@goldcrest.ae', '+971 4 422 4567', 'https://www.goldcrest.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@goldcrest.ae'),
      ('Habtoor City', 'brokers@habtoor.com', '+971 4 343 5550', 'https://www.alhabtoorcity.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@habtoor.com'),
      ('Hartland Estates (Sobha)', 'channelpartners@sobharealty.com', '+971 800 999 999', 'https://www.sobhahartland.com', 'Dubai', NULL, 'Channel Partners', NULL, 'channelpartners@sobharealty.com'),
      ('HDS Business Centre', 'brokers@hds.ae', '+971 4 277 7990', 'https://www.hds.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@hds.ae'),
      ('Heights Real Estate', 'brokers@heights.ae', '+971 4 277 4880', 'https://www.heights.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@heights.ae'),
      ('Hira Real Estate', 'brokers@hirarealestate.com', '+971 4 553 9988', 'https://www.hirarealestate.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@hirarealestate.com'),
      ('Indigo Properties', 'brokers@indigoproperties.ae', '+971 4 422 1233', 'https://www.indigoproperties.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@indigoproperties.ae'),
      ('Innovate Living', 'brokers@innovateliving.com', '+971 4 553 0707', 'https://www.innovateliving.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@innovateliving.com'),
      ('Ishraqah Development', 'brokers@ishraqah.com', '+971 4 423 4500', 'https://www.ishraqah.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@ishraqah.com'),
      ('Jumeirah Golf Estates', 'brokers@jumeirahgolfestates.com', '+971 4 818 2000', 'https://www.jumeirahgolfestates.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@jumeirahgolfestates.com'),
      ('Jumeirah Group', 'brokers@jumeirah.com', '+971 4 364 7555', 'https://www.jumeirah.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@jumeirah.com'),
      ('Kalimat Properties', 'brokers@kalimatproperties.com', '+971 4 882 1666', 'https://www.kalimatproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@kalimatproperties.com'),
      ('Karma Developers', 'brokers@karmadevelopers.com', '+971 4 277 5252', 'https://www.karmadevelopers.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@karmadevelopers.com'),
      ('Khalifa Fund', 'brokers@khalifafund.ae', '+971 2 491 0000', 'https://www.khalifafund.ae', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@khalifafund.ae'),
      ('Khamas Group', 'brokers@khamas.ae', '+971 4 343 4546', 'https://www.khamas.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@khamas.ae'),
      ('Kleindienst Group', 'brokers@kleindienst.com', '+971 4 422 9999', 'https://www.kleindienst.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@kleindienst.com'),
      ('Leos Developments', 'brokers@leosdevelopments.com', '+971 4 277 1444', 'https://www.leosdevelopments.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@leosdevelopments.com'),
      ('Limitless World', 'brokers@limitless.ae', '+971 4 388 4040', 'https://www.limitless.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@limitless.ae'),
      ('Luxe Developers', 'brokers@luxedevelopers.com', '+971 4 553 6666', 'https://www.luxedevelopers.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@luxedevelopers.com'),
      ('M Square Real Estate', 'brokers@msquare.ae', '+971 4 277 4477', 'https://www.msquare.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@msquare.ae'),
      ('Mada''in Properties', 'brokers@madain.ae', '+971 4 343 5455', 'https://www.madain.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@madain.ae'),
      ('Mag Lifestyle', 'brokers@mag.ae', '+971 4 422 4488', 'https://www.maglifestyledevelopment.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@mag.ae'),
      ('Marina Mansions', 'brokers@marinamansions.ae', '+971 4 422 0808', 'https://www.marinamansions.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@marinamansions.ae'),
      ('Marwa Developments', 'brokers@marwadevelopers.com', '+971 4 553 7100', 'https://www.marwadevelopers.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@marwadevelopers.com'),
      ('Mashriq Elite', 'brokers@mashriqelite.com', '+971 4 277 9494', 'https://www.mashriqelite.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@mashriqelite.com'),
      ('Mavida Real Estate', 'brokers@mavida.ae', '+971 4 388 1818', 'https://www.mavida.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@mavida.ae'),
      ('Maydan Group', 'brokers@maydangroup.com', '+971 4 327 0000', 'https://www.maydangroup.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@maydangroup.com'),
      ('MBK Real Estate', 'brokers@mbkre.ae', '+971 4 282 1212', 'https://www.mbkre.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@mbkre.ae'),
      ('MD Properties', 'brokers@mdproperties.ae', '+971 4 269 0099', 'https://www.mdproperties.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@mdproperties.ae'),
      ('Meraki Developers', 'brokers@merakidevelopers.com', '+971 4 553 8888', 'https://www.merakidevelopers.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@merakidevelopers.com'),
      ('Metac Real Estate', 'brokers@metac.ae', '+971 4 422 5544', 'https://www.metac.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@metac.ae'),
      ('Millennium Property Developers', 'brokers@millenniumdevelopers.ae', '+971 4 277 9444', 'https://www.millenniumdevelopers.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@millenniumdevelopers.ae'),
      ('Mira Group', 'brokers@miragroup.ae', '+971 4 234 0000', 'https://www.miragroup.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@miragroup.ae'),
      ('Mizin (Aldar)', 'brokers@aldar.com', '+971 2 810 5555', 'https://www.aldar.com', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@aldar.com'),
      ('Modular Living', 'brokers@modularliving.ae', '+971 4 553 9009', 'https://www.modularliving.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@modularliving.ae'),
      ('Mubarak Bin Mohammed', 'brokers@mbmuae.com', '+971 2 654 1010', 'https://www.mbmuae.com', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@mbmuae.com'),
      ('Naas Properties', 'brokers@naasproperties.com', '+971 4 553 4500', 'https://www.naasproperties.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@naasproperties.com'),
      ('National Bonds', 'brokers@nationalbonds.ae', '+971 4 422 6000', 'https://www.nationalbonds.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@nationalbonds.ae'),
      ('NBQ Investment', 'brokers@nbq.ae', '+971 7 207 0707', 'https://www.nbq.ae', 'Ras Al Khaimah', NULL, 'Broker Relations', NULL, 'brokers@nbq.ae'),
      ('Neo by Vincitore', 'brokers@vincitorerealestate.com', '+971 4 421 8788', 'https://www.vincitorerealestate.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@vincitorerealestate.com'),
      ('NSHAMA', 'brokers@nshama.ae', '+971 800 67426', 'https://www.nshama.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@nshama.ae'),
      ('OneOnly Resorts', 'brokers@oneandonlyresorts.com', '+971 4 440 1010', 'https://www.oneandonlyresorts.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@oneandonlyresorts.com'),
      ('Orchid Developers', 'brokers@orchiddevelopers.com', '+971 4 553 6500', 'https://www.orchiddevelopers.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@orchiddevelopers.com'),
      ('OTC Properties', 'brokers@otcproperties.ae', '+971 4 277 1111', 'https://www.otcproperties.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@otcproperties.ae'),
      ('Park Heights (Emaar)', 'brokers@emaar.ae', '+971 4 366 1688', 'https://www.emaar.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@emaar.ae'),
      ('Peace Homes Development', 'brokers@peacehomesgroup.com', '+971 4 277 5599', 'https://www.peacehomesgroup.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@peacehomesgroup.com'),
      ('Pearl Park Investment', 'brokers@pearlpark.ae', '+971 4 553 4567', 'https://www.pearlpark.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@pearlpark.ae'),
      ('Penthouse Properties', 'brokers@penthouseproperties.ae', '+971 4 268 8222', 'https://www.penthouseproperties.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@penthouseproperties.ae'),
      ('Pinnacle Real Estate', 'brokers@pinnaclerealestate.ae', '+971 4 422 7373', 'https://www.pinnaclerealestate.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@pinnaclerealestate.ae'),
      ('Pioneer Real Estate', 'brokers@pioneerproperties.com', '+971 4 553 9100', 'https://www.pioneerproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@pioneerproperties.com'),
      ('Premier Group', 'brokers@premieruae.com', '+971 4 388 1111', 'https://www.premieruae.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@premieruae.com'),
      ('Properties Investment LLC', 'brokers@piuae.com', '+971 4 343 9988', 'https://www.piuae.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@piuae.com'),
      ('Prescott Development', 'brokers@prescottdev.com', '+971 4 553 7373', 'https://www.prescottdev.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@prescottdev.com'),
      ('Quanta Investment', 'brokers@quanta.ae', '+971 4 282 8888', 'https://www.quanta.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@quanta.ae'),
      ('Rabdan Real Estate', 'brokers@rabdan.ae', '+971 4 277 8585', 'https://www.rabdan.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@rabdan.ae'),
      ('Radiant Capital', 'brokers@radiantcap.com', '+971 4 422 1199', 'https://www.radiantcap.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@radiantcap.com'),
      ('Reem Developers', 'brokers@reemdev.com', '+971 2 654 5555', 'https://www.reemdev.com', 'Abu Dhabi', NULL, 'Broker Relations', NULL, 'brokers@reemdev.com'),
      ('Reem Investments', 'brokers@reeminv.com', '+971 2 491 6000', 'https://www.reeminv.com', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@reeminv.com'),
      ('Riviera Group', 'brokers@rivieragroup.ae', '+971 4 422 5511', 'https://www.rivieragroup.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@rivieragroup.ae'),
      ('Royal Continental Hotels', 'brokers@royalcontinentalhotels.com', '+971 4 705 9999', 'https://www.royalcontinentalhotels.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@royalcontinentalhotels.com'),
      ('Royal Development', 'brokers@royaldevelopment.ae', '+971 4 553 6800', 'https://www.royaldevelopment.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@royaldevelopment.ae'),
      ('Roya Lifestyle Developments', 'brokers@royalifestyle.com', '+971 4 277 7100', 'https://www.royalifestyle.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@royalifestyle.com'),
      ('S&S Real Estate', 'brokers@sandsre.ae', '+971 4 422 5454', 'https://www.sandsre.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@sandsre.ae'),
      ('Saas Properties', 'brokers@saasproperties.com', '+971 4 553 7878', 'https://www.saasproperties.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@saasproperties.com'),
      ('Sahara Developers', 'brokers@saharadevelopers.ae', '+971 4 388 8484', 'https://www.saharadevelopers.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@saharadevelopers.ae'),
      ('Saif Belhasa Holding', 'brokers@saifbelhasa.com', '+971 4 343 8400', 'https://www.saifbelhasa.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@saifbelhasa.com'),
      ('Salwa Properties', 'brokers@salwa.ae', '+971 4 277 1660', 'https://www.salwa.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@salwa.ae'),
      ('Sankari Place', 'brokers@sankari.ae', '+971 4 333 7777', 'https://www.sankari.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@sankari.ae'),
      ('Saraya Holdings', 'brokers@saraya.com', '+971 4 432 7300', 'https://www.saraya.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@saraya.com'),
      ('Saud Bahwan Group', 'brokers@saudbahwan.com', '+971 4 553 7600', 'https://www.saudbahwan.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@saudbahwan.com'),
      ('Seven Skies Developments', 'brokers@sevenskiesdev.com', '+971 4 277 4400', 'https://www.sevenskiesdev.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@sevenskiesdev.com'),
      ('Sharaf Group', 'brokers@sharafgroup.com', '+971 4 388 5050', 'https://www.sharafgroup.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@sharafgroup.com'),
      ('Signature Developers', 'brokers@signaturedevelopers.ae', '+971 4 422 1199', 'https://www.signaturedevelopers.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@signaturedevelopers.ae'),
      ('Silverene (Dheeraj)', 'brokers@dheerajeastcoast.com', '+971 4 343 4744', 'https://www.dheerajeastcoast.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@dheerajeastcoast.com'),
      ('SOL Avenue', 'brokers@solproperties.ae', '+971 4 421 1110', 'https://www.solproperties.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@solproperties.ae'),
      ('Sortis Real Estate', 'brokers@sortis.ae', '+971 4 553 8585', 'https://www.sortis.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@sortis.ae'),
      ('Sphere Investments', 'brokers@sphereinv.com', '+971 4 422 7799', 'https://www.sphereinv.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@sphereinv.com'),
      ('Star Giga Real Estate', 'brokers@stargiga.ae', '+971 4 277 8181', 'https://www.stargiga.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@stargiga.ae'),
      ('Starz by Danube', 'channelpartners@danubeproperties.ae', '+971 4 244 3300', 'https://www.danubeproperties.ae', 'Dubai', NULL, 'Channel Partners', NULL, 'channelpartners@danubeproperties.ae'),
      ('Sunrise Homes', 'brokers@sunrisehomes.ae', '+971 4 553 9090', 'https://www.sunrisehomes.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@sunrisehomes.ae'),
      ('Sweidan Properties', 'brokers@sweidan.ae', '+971 4 277 7770', 'https://www.sweidan.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@sweidan.ae'),
      ('Tabeer Developments', 'brokers@tabeer.com', '+971 4 422 4222', 'https://www.tabeer.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@tabeer.com'),
      ('Taraf Holding', 'brokers@taraf.ae', '+971 4 277 0707', 'https://www.taraf.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@taraf.ae'),
      ('Tasmeer Real Estate', 'brokers@tasmeer.ae', '+971 4 553 7400', 'https://www.tasmeer.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@tasmeer.ae'),
      ('Tebyan Real Estate', 'brokers@tebyan.ae', '+971 2 491 5000', 'https://www.tebyan.ae', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@tebyan.ae'),
      ('Tecom Group', 'brokers@tecomgroup.ae', '+971 4 391 0000', 'https://www.tecomgroup.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@tecomgroup.ae'),
      ('The First Group', 'brokers@thefirstgroup.com', '+971 4 455 5800', 'https://www.thefirstgroup.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@thefirstgroup.com'),
      ('Triplanet Range', 'brokers@triplanetrange.com', '+971 4 277 4646', 'https://www.triplanetrange.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@triplanetrange.com'),
      ('Tuscany Real Estate', 'brokers@tuscany.ae', '+971 4 553 9494', 'https://www.tuscany.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@tuscany.ae'),
      ('Union Properties', 'brokers@up.ae', '+971 4 269 9991', 'https://www.up.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@up.ae'),
      ('United Arab Real Estate', 'brokers@uare.ae', '+971 4 422 8888', 'https://www.uare.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@uare.ae'),
      ('Vakson Real Estate', 'brokers@vakson.com', '+971 4 553 7575', 'https://www.vakson.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@vakson.com'),
      ('Vision Vista', 'brokers@visionvista.ae', '+971 4 277 9999', 'https://www.visionvista.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@visionvista.ae'),
      ('Vintage Bloom', 'brokers@vintagebloom.ae', '+971 4 553 8888', 'https://www.vintagebloom.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@vintagebloom.ae'),
      ('VRS Real Estate', 'brokers@vrs.ae', '+971 4 422 4400', 'https://www.vrs.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@vrs.ae'),
      ('Wahat Al Zaweya', 'brokers@wahatalzaweya.com', '+971 2 654 7000', 'https://www.wahatalzaweya.com', 'Abu Dhabi', NULL, 'Broker Relations', NULL, 'brokers@wahatalzaweya.com'),
      ('Waterfront Real Estate', 'brokers@waterfront.ae', '+971 4 553 8484', 'https://www.waterfront.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@waterfront.ae'),
      ('XYZ Developers', 'brokers@xyzdevelopers.ae', '+971 4 422 5959', 'https://www.xyzdevelopers.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@xyzdevelopers.ae'),
      ('Yas Acres (Aldar)', 'brokers@aldar.com', '+971 2 810 5555', 'https://www.aldar.com', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@aldar.com'),
      ('Zaya Real Estate', 'brokers@zaya.ae', '+971 4 814 5500', 'https://www.zaya.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@zaya.ae'),
      ('Zoha Real Estate', 'brokers@zoharealestate.com', '+971 4 553 9595', 'https://www.zoharealestate.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@zoharealestate.com'),
      ('Almal Real Estate', 'brokers@almalre.com', '+971 4 422 0099', 'https://www.almalre.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@almalre.com'),
      ('Pure Harvest', 'brokers@pureharvest.ae', '+971 2 491 8000', 'https://www.pureharvest.ae', 'Abu Dhabi', NULL, 'Broker Desk', NULL, 'brokers@pureharvest.ae'),
      ('Royal Estates', 'brokers@royalestates.ae', '+971 4 553 6700', 'https://www.royalestates.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@royalestates.ae'),
      ('AG Square Real Estate', 'brokers@agsquare.ae', '+971 4 277 3322', 'https://www.agsquare.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@agsquare.ae'),
      ('Ahmad Tea Properties', 'brokers@ahmadtea.ae', '+971 4 422 7676', 'https://www.ahmadtea.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@ahmadtea.ae'),
      ('Iconic Properties', 'brokers@iconicproperties.ae', '+971 4 553 7676', 'https://www.iconicproperties.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@iconicproperties.ae'),
      ('Casabella Lifestyle', 'brokers@casabella.ae', '+971 4 277 4848', 'https://www.casabella.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@casabella.ae'),
      ('Helio Real Estate', 'brokers@heliore.com', '+971 4 422 7373', 'https://www.heliore.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@heliore.com'),
      ('Lacasa Properties', 'brokers@lacasa.ae', '+971 4 553 7474', 'https://www.lacasa.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@lacasa.ae'),
      ('Vision Real Estate', 'brokers@visionre.ae', '+971 4 277 9292', 'https://www.visionre.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@visionre.ae'),
      ('Apex Properties', 'brokers@apexproperties.ae', '+971 4 422 5252', 'https://www.apexproperties.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@apexproperties.ae'),
      ('Trio Properties', 'brokers@trioproperties.ae', '+971 4 553 8181', 'https://www.trioproperties.ae', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@trioproperties.ae'),
      ('Skyhigh Developers', 'brokers@skyhigh.ae', '+971 4 277 6868', 'https://www.skyhigh.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@skyhigh.ae'),
      ('Royal Park Investments', 'brokers@royalparkinv.com', '+971 4 422 4848', 'https://www.royalparkinv.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@royalparkinv.com'),
      ('Heart of Europe (Kleindienst)', 'brokers@kleindienst.com', '+971 4 422 9999', 'https://www.theheartofeurope.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@kleindienst.com'),
      ('Rasamny Holdings', 'brokers@rasamny.com', '+971 4 277 4040', 'https://www.rasamny.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@rasamny.com'),
      ('IGO Properties', 'brokers@igoproperties.ae', '+971 4 422 6363', 'https://www.igoproperties.ae', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@igoproperties.ae'),
      ('Marquis Point', 'brokers@marquispoint.com', '+971 4 553 5252', 'https://www.marquispoint.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@marquispoint.com'),
      ('Acuity Real Estate', 'brokers@acuityre.com', '+971 4 277 8989', 'https://www.acuityre.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@acuityre.com'),
      ('Nine Yards Plus', 'brokers@nineyardsplus.com', '+971 4 422 9292', 'https://www.nineyardsplus.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@nineyardsplus.com'),
      ('IRTH (Aldar)', 'brokers@aldar.com', '+971 2 810 5555', 'https://www.aldar.com', 'Abu Dhabi', NULL, 'Broker Relations', NULL, 'brokers@aldar.com'),
      ('Nine by Bin Faqeeh', 'brokers@binfaqeeh.com', '+971 4 553 9991', 'https://www.binfaqeeh.com', 'Dubai', NULL, 'Broker Desk', NULL, 'brokers@binfaqeeh.com'),
      ('FIVE Palm Jumeirah', 'brokers@fivehotelsandresorts.com', '+971 4 455 9989', 'https://www.fivehotelsandresorts.com', 'Dubai', NULL, 'Broker Relations', NULL, 'brokers@fivehotelsandresorts.com')
    ) AS t(name, email, phone, website, emirate, contact_name, contact_role, contact_phone, contact_email)
  LOOP
    v_slug := lower(regexp_replace(regexp_replace(v_dev.name, '[^a-zA-Z0-9 -]', '', 'g'), '\s+', '-', 'g'));

    INSERT INTO public.crm_developer_registry (
      owner_id, developer_name, developer_slug, developer_email, phone, website, emirate,
      developer_contact, status, required_docs_complete, priority
    ) VALUES (
      p_owner_id, v_dev.name, v_slug, v_dev.email, v_dev.phone, v_dev.website, v_dev.emirate,
      jsonb_strip_nulls(jsonb_build_object(
        'name', v_dev.contact_name,
        'role', v_dev.contact_role,
        'phone', v_dev.contact_phone,
        'email', v_dev.contact_email
      )),
      'not_started', false, 'medium'
    )
    ON CONFLICT (owner_id, developer_slug) DO UPDATE SET
      developer_email = COALESCE(crm_developer_registry.developer_email, EXCLUDED.developer_email),
      phone = COALESCE(crm_developer_registry.phone, EXCLUDED.phone),
      website = COALESCE(crm_developer_registry.website, EXCLUDED.website),
      emirate = COALESCE(crm_developer_registry.emirate, EXCLUDED.emirate),
      developer_contact = CASE
        WHEN crm_developer_registry.developer_contact IS NULL OR crm_developer_registry.developer_contact = '{}'::jsonb
          THEN EXCLUDED.developer_contact
        ELSE crm_developer_registry.developer_contact
      END;

    v_count := v_count + 1;
  END LOOP;

  RETURN v_count;
END;
$function$;