REVOKE SELECT ON public.developers FROM anon;

GRANT SELECT (
  id,
  name,
  slug,
  logo_url,
  logo_url_processed,
  logo_url_dark,
  logo_bg_color,
  description,
  description_languages,
  rank,
  founded_year,
  completed_projects,
  offplan_projects,
  portfolio_worth,
  headquarters,
  feature_image_url,
  website_url,
  total_units_delivered,
  upcoming_units,
  expected_completion_year,
  notable_projects,
  parent_company,
  specialization,
  is_hidden,
  instagram_url,
  linkedin_url,
  google_maps_url,
  trust_level,
  has_active_rep,
  public_fields,
  is_manually_verified,
  created_at,
  updated_at
) ON public.developers TO anon;