INSERT INTO public.ai_tool_visibility (tool_id, visibility, is_public) VALUES
  ('ai-video-studio','hidden',false),
  ('video-resize-pack','hidden',false),
  ('voice-studio','hidden',false),
  ('pdf-from-photos','hidden',false),
  ('image-resize','hidden',false),
  ('captions-translate','hidden',false),
  ('background-ai','hidden',false),
  ('beauty-filters','hidden',false),
  ('creative-suite','hidden',false),
  ('interior-design-ai','hidden',false),
  ('virtual-staging-ai','hidden',false),
  ('ai-lead-qualification','hidden',false),
  ('ai-followup-scheduler','hidden',false),
  ('ai-objection-handler','hidden',false),
  ('ai-client-matcher','hidden',false),
  ('ai-market-report','hidden',false),
  ('ai-competitor-analysis','hidden',false),
  ('ai-roi-calculator','hidden',false),
  ('ai-investment-report','hidden',false),
  ('ai-meeting-summarizer','hidden',false),
  ('ai-translation-hub','hidden',false),
  ('ai-video-tour-script','hidden',false),
  ('ai-email-generator','hidden',false),
  ('ai-social-media','hidden',false),
  ('ai-description-writer','hidden',false),
  ('ai-contract-reviewer','hidden',false),
  ('ai-document-generator','hidden',false),
  ('stamp-generator','hidden',false),
  ('scan-sign','hidden',false),
  ('business-card-scanner','hidden',false),
  ('documents','hidden',false),
  ('video-meeting','hidden',false),
  ('ai-calendar','hidden',false),
  ('ai-home-finder','public',true),
  ('property-comparison','public',true),
  ('property-evaluator','public',true),
  ('rental-index','public',true),
  ('mortgage-calculator','public',true)
ON CONFLICT (tool_id) DO UPDATE SET
  visibility = EXCLUDED.visibility,
  is_public  = EXCLUDED.is_public,
  updated_at = now();